<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest\Device;

use UnexpectedValueException;

/**
 * The type of device on which the ad will be shown.
 *
 * Protobuf type <code>BidRequest.Device.DeviceType</code>
 */
class DeviceType
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_DEVICE = 0;</code>
     */
    const UNKNOWN_DEVICE = 0;
    /**
     * Generated from protobuf enum <code>HIGHEND_PHONE = 1;</code>
     */
    const HIGHEND_PHONE = 1;
    /**
     * Generated from protobuf enum <code>TABLET = 2;</code>
     */
    const TABLET = 2;
    /**
     * Desktop or laptop devices.
     *
     * Generated from protobuf enum <code>PERSONAL_COMPUTER = 3;</code>
     */
    const PERSONAL_COMPUTER = 3;
    /**
     * Both connected TVs (that is, smart TVs) and connected devices
     * (such as Roku and Apple TV).
     *
     * Generated from protobuf enum <code>CONNECTED_TV = 4;</code>
     */
    const CONNECTED_TV = 4;
    /**
     * Generated from protobuf enum <code>GAME_CONSOLE = 5;</code>
     */
    const GAME_CONSOLE = 5;
    /**
     * Generated from protobuf enum <code>SET_TOP_BOX = 6;</code>
     */
    const SET_TOP_BOX = 6;

    private static $valueToName = [
        self::UNKNOWN_DEVICE => 'UNKNOWN_DEVICE',
        self::HIGHEND_PHONE => 'HIGHEND_PHONE',
        self::TABLET => 'TABLET',
        self::PERSONAL_COMPUTER => 'PERSONAL_COMPUTER',
        self::CONNECTED_TV => 'CONNECTED_TV',
        self::GAME_CONSOLE => 'GAME_CONSOLE',
        self::SET_TOP_BOX => 'SET_TOP_BOX',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(DeviceType::class, \BidRequest_Device_DeviceType::class);

