<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest\Device;

use UnexpectedValueException;

/**
 * [default = 0];
 *
 * Protobuf type <code>BidRequest.Device.ScreenOrientation</code>
 */
class ScreenOrientation
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_ORIENTATION = 0;</code>
     */
    const UNKNOWN_ORIENTATION = 0;
    /**
     * Generated from protobuf enum <code>PORTRAIT = 1;</code>
     */
    const PORTRAIT = 1;
    /**
     * Generated from protobuf enum <code>LANDSCAPE = 2;</code>
     */
    const LANDSCAPE = 2;

    private static $valueToName = [
        self::UNKNOWN_ORIENTATION => 'UNKNOWN_ORIENTATION',
        self::PORTRAIT => 'PORTRAIT',
        self::LANDSCAPE => 'LANDSCAPE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ScreenOrientation::class, \BidRequest_Device_ScreenOrientation::class);

