<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest\AdSlot;

use UnexpectedValueException;

/**
 * Possible ad rendering API frameworks that can be supported.
 * If an API is not explicitly listed, it is assumed not to be supported.
 *
 * Protobuf type <code>BidRequest.AdSlot.APIFramework</code>
 */
class APIFramework
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_FRAMEWORK = 0;</code>
     */
    const UNKNOWN_FRAMEWORK = 0;
    /**
     * Mobile Rich Media Ad Interface Definitions Version 1.0. See
     * https://www.iab.com/guidelines/mraid/.
     *
     * Generated from protobuf enum <code>MRAID_1 = 3;</code>
     */
    const MRAID_1 = 3;
    /**
     * Mobile Rich Media Ad Interface Definitions Version 2.0. See
     * https://www.iab.com/guidelines/mraid/.
     *
     * Generated from protobuf enum <code>MRAID_2 = 5;</code>
     */
    const MRAID_2 = 5;
    /**
     * Mobile Rich Media Ad Interface Definitions Version 3.0. See
     * https://www.iab.com/guidelines/mraid/.
     *
     * Generated from protobuf enum <code>MRAID_3 = 6;</code>
     */
    const MRAID_3 = 6;
    /**
     * Open Measurement Interface Definition Version 1.0. See
     * https://iabtechlab.com/standards/open-measurement-sdk/.
     *
     * Generated from protobuf enum <code>OMID_1 = 7;</code>
     */
    const OMID_1 = 7;

    private static $valueToName = [
        self::UNKNOWN_FRAMEWORK => 'UNKNOWN_FRAMEWORK',
        self::MRAID_1 => 'MRAID_1',
        self::MRAID_2 => 'MRAID_2',
        self::MRAID_3 => 'MRAID_3',
        self::OMID_1 => 'OMID_1',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(APIFramework::class, \BidRequest_AdSlot_APIFramework::class);

