<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest\AdSlot;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Indicates the creative policy and publisher blocks that applies to this
 * request.
 *
 * Generated from protobuf message <code>BidRequest.AdSlot.CreativeEnforcementSettings</code>
 */
class CreativeEnforcementSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .BidRequest.AdSlot.CreativeEnforcementSettings.PolicyEnforcement policy_enforcement = 1;</code>
     */
    protected $policy_enforcement = null;
    /**
     * Generated from protobuf field <code>optional .BidRequest.AdSlot.CreativeEnforcementSettings.PublisherBlocksEnforcement publisher_blocks_enforcement = 3;</code>
     */
    protected $publisher_blocks_enforcement = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $policy_enforcement
     *     @type int $publisher_blocks_enforcement
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RealtimeBidding::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .BidRequest.AdSlot.CreativeEnforcementSettings.PolicyEnforcement policy_enforcement = 1;</code>
     * @return int
     */
    public function getPolicyEnforcement()
    {
        return isset($this->policy_enforcement) ? $this->policy_enforcement : 0;
    }

    public function hasPolicyEnforcement()
    {
        return isset($this->policy_enforcement);
    }

    public function clearPolicyEnforcement()
    {
        unset($this->policy_enforcement);
    }

    /**
     * Generated from protobuf field <code>optional .BidRequest.AdSlot.CreativeEnforcementSettings.PolicyEnforcement policy_enforcement = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPolicyEnforcement($var)
    {
        GPBUtil::checkEnum($var, \BidRequest\AdSlot\CreativeEnforcementSettings\PolicyEnforcement::class);
        $this->policy_enforcement = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .BidRequest.AdSlot.CreativeEnforcementSettings.PublisherBlocksEnforcement publisher_blocks_enforcement = 3;</code>
     * @return int
     */
    public function getPublisherBlocksEnforcement()
    {
        return isset($this->publisher_blocks_enforcement) ? $this->publisher_blocks_enforcement : 0;
    }

    public function hasPublisherBlocksEnforcement()
    {
        return isset($this->publisher_blocks_enforcement);
    }

    public function clearPublisherBlocksEnforcement()
    {
        unset($this->publisher_blocks_enforcement);
    }

    /**
     * Generated from protobuf field <code>optional .BidRequest.AdSlot.CreativeEnforcementSettings.PublisherBlocksEnforcement publisher_blocks_enforcement = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPublisherBlocksEnforcement($var)
    {
        GPBUtil::checkEnum($var, \BidRequest\AdSlot\CreativeEnforcementSettings\PublisherBlocksEnforcement::class);
        $this->publisher_blocks_enforcement = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(CreativeEnforcementSettings::class, \BidRequest_AdSlot_CreativeEnforcementSettings::class);

