<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest\AdSlot;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A creative that is disallowed to bid on this impression due to Ad
 * Exchange policies or creative disapproval, excluded creative attributes,
 * excluded product or sensitive categories, allowed vendor types,
 * restricted categories or languages applicable to the bid request.
 *
 * Generated from protobuf message <code>BidRequest.AdSlot.ExcludedCreative</code>
 */
class ExcludedCreative extends \Google\Protobuf\Internal\Message
{
    /**
     * Buyer creative ID of the disallowed creative.
     *
     * Generated from protobuf field <code>optional string buyer_creative_id = 1;</code>
     */
    protected $buyer_creative_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $buyer_creative_id
     *           Buyer creative ID of the disallowed creative.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RealtimeBidding::initOnce();
        parent::__construct($data);
    }

    /**
     * Buyer creative ID of the disallowed creative.
     *
     * Generated from protobuf field <code>optional string buyer_creative_id = 1;</code>
     * @return string
     */
    public function getBuyerCreativeId()
    {
        return isset($this->buyer_creative_id) ? $this->buyer_creative_id : '';
    }

    public function hasBuyerCreativeId()
    {
        return isset($this->buyer_creative_id);
    }

    public function clearBuyerCreativeId()
    {
        unset($this->buyer_creative_id);
    }

    /**
     * Buyer creative ID of the disallowed creative.
     *
     * Generated from protobuf field <code>optional string buyer_creative_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBuyerCreativeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->buyer_creative_id = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ExcludedCreative::class, \BidRequest_AdSlot_ExcludedCreative::class);

