<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest\AdSlot;

use UnexpectedValueException;

/**
 * iFrame depth of the ad slot on the webpage where it is present.
 * Currently only set for video ad requests.
 *
 * Protobuf type <code>BidRequest.AdSlot.IFramingDepth</code>
 */
class IFramingDepth
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_IFRAME_DEPTH = 0;</code>
     */
    const UNKNOWN_IFRAME_DEPTH = 0;
    /**
     * Generated from protobuf enum <code>NOT_IN_IFRAME = 1;</code>
     */
    const NOT_IN_IFRAME = 1;
    /**
     * Generated from protobuf enum <code>ONE_IFRAME = 2;</code>
     */
    const ONE_IFRAME = 2;
    /**
     * Generated from protobuf enum <code>MULTIPLE_IFRAME = 3;</code>
     */
    const MULTIPLE_IFRAME = 3;

    private static $valueToName = [
        self::UNKNOWN_IFRAME_DEPTH => 'UNKNOWN_IFRAME_DEPTH',
        self::NOT_IN_IFRAME => 'NOT_IN_IFRAME',
        self::ONE_IFRAME => 'ONE_IFRAME',
        self::MULTIPLE_IFRAME => 'MULTIPLE_IFRAME',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(IFramingDepth::class, \BidRequest_AdSlot_IFramingDepth::class);

