<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest\AdSlot;

use UnexpectedValueException;

/**
 * iFraming state of the ad slot on the webpage where it is present.
 *
 * Protobuf type <code>BidRequest.AdSlot.IFramingState</code>
 */
class IFramingState
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_IFRAME_STATE = 0;</code>
     */
    const UNKNOWN_IFRAME_STATE = 0;
    /**
     * Generated from protobuf enum <code>NO_IFRAME = 1;</code>
     */
    const NO_IFRAME = 1;
    /**
     * Generated from protobuf enum <code>SAME_DOMAIN_IFRAME = 2;</code>
     */
    const SAME_DOMAIN_IFRAME = 2;
    /**
     * Generated from protobuf enum <code>CROSS_DOMAIN_IFRAME = 3;</code>
     */
    const CROSS_DOMAIN_IFRAME = 3;

    private static $valueToName = [
        self::UNKNOWN_IFRAME_STATE => 'UNKNOWN_IFRAME_STATE',
        self::NO_IFRAME => 'NO_IFRAME',
        self::SAME_DOMAIN_IFRAME => 'SAME_DOMAIN_IFRAME',
        self::CROSS_DOMAIN_IFRAME => 'CROSS_DOMAIN_IFRAME',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(IFramingState::class, \BidRequest_AdSlot_IFramingState::class);

