<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest\AdSlot;

use UnexpectedValueException;

/**
 * Sources for non-browser inventory.
 *
 * Protobuf type <code>BidRequest.AdSlot.NonBrowserSource</code>
 */
class NonBrowserSource
{
    /**
     * Generated from protobuf enum <code>UNDECLARED_SOURCE = 0;</code>
     */
    const UNDECLARED_SOURCE = 0;
    /**
     * Generated from protobuf enum <code>DESKTOP_APP = 1;</code>
     */
    const DESKTOP_APP = 1;

    private static $valueToName = [
        self::UNDECLARED_SOURCE => 'UNDECLARED_SOURCE',
        self::DESKTOP_APP => 'DESKTOP_APP',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(NonBrowserSource::class, \BidRequest_AdSlot_NonBrowserSource::class);

