<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest\AdSlot;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Secure signals passed by the publisher.
 *
 * Generated from protobuf message <code>BidRequest.AdSlot.SecureSignal</code>
 */
class SecureSignal extends \Google\Protobuf\Internal\Message
{
    /**
     * The source (provider) of the signal. Identifier for the library or SDK
     * that generated this data.
     *
     * Generated from protobuf field <code>optional string source = 4;</code>
     */
    protected $source = null;
    /**
     * The secure signal.
     *
     * Generated from protobuf field <code>optional string data = 2;</code>
     */
    protected $data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $source
     *           The source (provider) of the signal. Identifier for the library or SDK
     *           that generated this data.
     *     @type string $data
     *           The secure signal.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RealtimeBidding::initOnce();
        parent::__construct($data);
    }

    /**
     * The source (provider) of the signal. Identifier for the library or SDK
     * that generated this data.
     *
     * Generated from protobuf field <code>optional string source = 4;</code>
     * @return string
     */
    public function getSource()
    {
        return isset($this->source) ? $this->source : '';
    }

    public function hasSource()
    {
        return isset($this->source);
    }

    public function clearSource()
    {
        unset($this->source);
    }

    /**
     * The source (provider) of the signal. Identifier for the library or SDK
     * that generated this data.
     *
     * Generated from protobuf field <code>optional string source = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->source = $var;

        return $this;
    }

    /**
     * The secure signal.
     *
     * Generated from protobuf field <code>optional string data = 2;</code>
     * @return string
     */
    public function getData()
    {
        return isset($this->data) ? $this->data : '';
    }

    public function hasData()
    {
        return isset($this->data);
    }

    public function clearData()
    {
        unset($this->data);
    }

    /**
     * The secure signal.
     *
     * Generated from protobuf field <code>optional string data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, True);
        $this->data = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(SecureSignal::class, \BidRequest_AdSlot_SecureSignal::class);

