<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>BidResponse.Ad</code>
 */
class Ad extends \Google\Protobuf\Internal\Message
{
    /**
     * The event notification token is sent to AdX by bidders for
     * troubleshooting. AdX will include the token in real-time feedback for the
     * bid. The content of the token will not be logged by AdX. AdX will ignore
     * any token longer than 128 bytes.
     *
     * Generated from protobuf field <code>optional bytes event_notification_token = 25;</code>
     */
    protected $event_notification_token = null;
    /**
     * A unique identifier chosen by you for the creative in this response.
     * This must always be set, must be limited to at most 64 bytes, and must be
     * a valid UTF8 string. Every buyer_creative_id you use must always be
     * associated with the same creative. This field is used to communicate
     * approval statuses when issues are found. Do not specify the same id for
     * different creatives, or all creatives will be disapproved if a problem
     * with a single creative is found. Do not specify different ids for the
     * same creative in different responses or no creatives will be served since
     * approval status is assigned on a per-id basis.
     *
     * Generated from protobuf field <code>optional string buyer_creative_id = 10;</code>
     */
    protected $buyer_creative_id = null;
    /**
     * Only one of the following should be set:
     * 1) html_snippet, 2) video_url, 3) native_ad, or 4) sdk_rendered_ad.
     * The HTML snippet that will be placed on the web page to display the ad.
     * Use BidResponse.Ad.AdSlot.billing_id to indicate which billing id
     * this snippet is attributed to.
     *
     * Generated from protobuf field <code>optional string html_snippet = 1;</code>
     */
    protected $html_snippet = null;
    /**
     * The URL to fetch a video ad. The URL should return an XML response that
     * conforms to the VAST 2.0 or 3.0 standard. Use
     * BidResponse.Ad.AdSlot.billing_id to indicate which billing id to
     * attribute this ad to. Only one of the following should be set:
     * html_snippet, video_url. Only set this field if the BidRequest is for an
     * in-video ad (BidRequest.video is present).
     *
     * Generated from protobuf field <code>optional string video_url = 9;</code>
     */
    protected $video_url = null;
    /**
     * The VAST document to be returned. This document should conform to the
     * VAST 2.0 or 3.0 standard. Use BidResponse.Ad.AdSlot.billing_id to
     * indicate which billing ID to attribute this ad to.
     * Only set this field if the BidRequest is for an in-video ad and the
     * response is VAST XML.
     *
     * Generated from protobuf field <code>optional string video_vast_xml = 24;</code>
     */
    protected $video_vast_xml = null;
    /**
     * The URL to fetch an AMPHTML ad. Only one of the following should be set:
     * html_snippet, video_url, amp_ad_url, native_ad.
     *
     * Generated from protobuf field <code>optional string amp_ad_url = 23;</code>
     */
    protected $amp_ad_url = null;
    /**
     * Generated from protobuf field <code>optional .BidResponse.Ad.NativeAd native_ad = 18;</code>
     */
    protected $native_ad = null;
    /**
     * The set of destination URLs for the snippet. This includes the URLs that
     * the user will go to if they click on the displayed ad, and any URLs that
     * are visible in the rendered ad. Do not include intermediate calls to the
     * adserver that are unrelated to the inal landing page. A BidResponse that
     * returns a snippet or video ad but declares no click_through_url will be
     * discarded. Only set this field if html_snippet or video_url or native_ad
     * are set. This data is used as a destination URL declaration, for example
     * for post-filtering of publisher-blocked URLs or ad categorization.
     * For non-native ads, it is not used for click tracking or any
     * other ad functionality; it is only used as a destination URL
     * declaration.
     * For native ads, if NativeAd.click_link_url is not set, the first
     * value of click_through_url is used to direct the user to the landing
     * page. In addition, all values are used as destination
     * URL declarations (similar to the non-native case).
     *
     * Generated from protobuf field <code>repeated string click_through_url = 4;</code>
     */
    private $click_through_url;
    /**
     * All vendor types for the ads that may be shown from this snippet. You
     * should only declare vendor ids listed in the vendors.txt file in the
     * technical documentation. We will check to ensure that the vendors you
     * declare are in the allowed_vendor_type list sent in the BidRequest for
     * AdX publishers.
     *
     * Generated from protobuf field <code>repeated int32 vendor_type = 5;</code>
     */
    private $vendor_type;
    /**
     * All attributes for the ads that may be shown from this snippet. See
     * buyer-declarable-creative-attributes.txt in the technical documentation
     * for a list of ids. We will check to ensure none of these attributes are
     * in the excluded_attribute list in the BidRequest.
     *
     * Generated from protobuf field <code>repeated int32 attribute = 6;</code>
     */
    private $attribute;
    /**
     * All sensitive categories for the ads that may be shown from this snippet.
     * See ad-sensitive-categories.txt in the technical documentation for a list
     * of ids. We will check to ensure none of these categories were in the
     * excluded_sensitive_category list in the BidRequest.
     *
     * Generated from protobuf field <code>repeated int32 category = 7;</code>
     */
    private $category;
    /**
     * All restricted categories for the ads that may be shown from this
     * snippet. See ad-restricted-categories.txt in the technical documentation
     * for a list of ids. We will check to ensure these categories were listed
     * in the allowed_restricted_category list in the BidRequest. If you are
     * bidding with ads in restricted categories you MUST ALWAYS declare them
     * here.
     *
     * Generated from protobuf field <code>repeated int32 restricted_category = 17;</code>
     */
    private $restricted_category;
    /**
     * All names of the ad's advertisers.
     *
     * Generated from protobuf field <code>repeated string advertiser_name = 11;</code>
     */
    private $advertiser_name;
    /**
     * The width and the height in pixels of the ad. Setting these is optional.
     * However, these must be set if the bid BidRequest.AdSlot has more than one
     * width and height or if BidRequest.Mobile.is_interstitial_request is true.
     *
     * Generated from protobuf field <code>optional int32 width = 14;</code>
     */
    protected $width = null;
    /**
     * Generated from protobuf field <code>optional int32 height = 15;</code>
     */
    protected $height = null;
    /**
     * Generated from protobuf field <code>repeated .BidResponse.Ad.AdSlot adslot = 3;</code>
     */
    private $adslot;
    /**
     * The URLs to call when the impression is rendered. This is supported for
     * all inventory types and all formats.
     *
     * Generated from protobuf field <code>repeated string impression_tracking_url = 19;</code>
     */
    private $impression_tracking_url;
    /**
     * The URLs to call when the user clicks on the ad. Currently supported only
     * for native ads and Programmatic Guaranteed deals with publisher-
     * managed creatives. In the publisher managed case, these click trackers
     * will be sent to the bidder server to server. In all other cases, these
     * will be sent from the user's device. For more information on
     * publisher-managed creatives, see
     * https://support.google.com/admanager/answer/9243220.
     *
     * Generated from protobuf field <code>repeated string click_tracking_urls = 30;</code>
     */
    private $click_tracking_urls;
    /**
     * Link to ad preferences page. This is only supported for native ads.
     * If present, a standard AdChoices icon is added to the native creative and
     * linked to this URL.
     *
     * Generated from protobuf field <code>optional string ad_choices_destination_url = 21;</code>
     */
    protected $ad_choices_destination_url = null;
    /**
     * Resources to invoke when the impression is rendered. This is supported
     * for native and banner formats only and explicitly allowed scripts
     * only.
     *
     * Generated from protobuf field <code>repeated .BidResponse.Ad.ImpressionTrackingResource impression_tracking_resource = 26;</code>
     */
    private $impression_tracking_resource;
    /**
     * Generated from protobuf field <code>optional .BidResponse.Ad.SdkRenderedAd sdk_rendered_ad = 27;</code>
     */
    protected $sdk_rendered_ad = null;
    /**
     * Generated from protobuf field <code>optional .BidResponse.Ad.SKAdNetworkResponse skadn = 29;</code>
     */
    protected $skadn = null;
    /**
     * ID of the advertised app (only for app promotion).
     * On Android, this should be a bundle or package name such as
     * com.foo.mygame. On iOS, it is a numeric ID.
     * In addition to this field, set the app_promotion_type field below to take
     * advantage of features specific to app promotion types.
     *
     * Generated from protobuf field <code>optional string advertised_app_id = 32;</code>
     */
    protected $advertised_app_id = null;
    /**
     * Type of the app promotion corresponding to the advertised app specified
     * in the advertised_app_id field above.
     * If the advertised app is not specified, this field will be ignored.
     * Setting advertised_app_id field without this field will be treated as if
     * this field were set to OTHER.
     *
     * Generated from protobuf field <code>optional .BidResponse.Ad.AppPromotionType app_promotion_type = 33;</code>
     */
    protected $app_promotion_type = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $event_notification_token
     *           The event notification token is sent to AdX by bidders for
     *           troubleshooting. AdX will include the token in real-time feedback for the
     *           bid. The content of the token will not be logged by AdX. AdX will ignore
     *           any token longer than 128 bytes.
     *     @type string $buyer_creative_id
     *           A unique identifier chosen by you for the creative in this response.
     *           This must always be set, must be limited to at most 64 bytes, and must be
     *           a valid UTF8 string. Every buyer_creative_id you use must always be
     *           associated with the same creative. This field is used to communicate
     *           approval statuses when issues are found. Do not specify the same id for
     *           different creatives, or all creatives will be disapproved if a problem
     *           with a single creative is found. Do not specify different ids for the
     *           same creative in different responses or no creatives will be served since
     *           approval status is assigned on a per-id basis.
     *     @type string $html_snippet
     *           Only one of the following should be set:
     *           1) html_snippet, 2) video_url, 3) native_ad, or 4) sdk_rendered_ad.
     *           The HTML snippet that will be placed on the web page to display the ad.
     *           Use BidResponse.Ad.AdSlot.billing_id to indicate which billing id
     *           this snippet is attributed to.
     *     @type string $video_url
     *           The URL to fetch a video ad. The URL should return an XML response that
     *           conforms to the VAST 2.0 or 3.0 standard. Use
     *           BidResponse.Ad.AdSlot.billing_id to indicate which billing id to
     *           attribute this ad to. Only one of the following should be set:
     *           html_snippet, video_url. Only set this field if the BidRequest is for an
     *           in-video ad (BidRequest.video is present).
     *     @type string $video_vast_xml
     *           The VAST document to be returned. This document should conform to the
     *           VAST 2.0 or 3.0 standard. Use BidResponse.Ad.AdSlot.billing_id to
     *           indicate which billing ID to attribute this ad to.
     *           Only set this field if the BidRequest is for an in-video ad and the
     *           response is VAST XML.
     *     @type string $amp_ad_url
     *           The URL to fetch an AMPHTML ad. Only one of the following should be set:
     *           html_snippet, video_url, amp_ad_url, native_ad.
     *     @type \BidResponse\Ad\NativeAd $native_ad
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $click_through_url
     *           The set of destination URLs for the snippet. This includes the URLs that
     *           the user will go to if they click on the displayed ad, and any URLs that
     *           are visible in the rendered ad. Do not include intermediate calls to the
     *           adserver that are unrelated to the inal landing page. A BidResponse that
     *           returns a snippet or video ad but declares no click_through_url will be
     *           discarded. Only set this field if html_snippet or video_url or native_ad
     *           are set. This data is used as a destination URL declaration, for example
     *           for post-filtering of publisher-blocked URLs or ad categorization.
     *           For non-native ads, it is not used for click tracking or any
     *           other ad functionality; it is only used as a destination URL
     *           declaration.
     *           For native ads, if NativeAd.click_link_url is not set, the first
     *           value of click_through_url is used to direct the user to the landing
     *           page. In addition, all values are used as destination
     *           URL declarations (similar to the non-native case).
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $vendor_type
     *           All vendor types for the ads that may be shown from this snippet. You
     *           should only declare vendor ids listed in the vendors.txt file in the
     *           technical documentation. We will check to ensure that the vendors you
     *           declare are in the allowed_vendor_type list sent in the BidRequest for
     *           AdX publishers.
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $attribute
     *           All attributes for the ads that may be shown from this snippet. See
     *           buyer-declarable-creative-attributes.txt in the technical documentation
     *           for a list of ids. We will check to ensure none of these attributes are
     *           in the excluded_attribute list in the BidRequest.
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $category
     *           All sensitive categories for the ads that may be shown from this snippet.
     *           See ad-sensitive-categories.txt in the technical documentation for a list
     *           of ids. We will check to ensure none of these categories were in the
     *           excluded_sensitive_category list in the BidRequest.
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $restricted_category
     *           All restricted categories for the ads that may be shown from this
     *           snippet. See ad-restricted-categories.txt in the technical documentation
     *           for a list of ids. We will check to ensure these categories were listed
     *           in the allowed_restricted_category list in the BidRequest. If you are
     *           bidding with ads in restricted categories you MUST ALWAYS declare them
     *           here.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $advertiser_name
     *           All names of the ad's advertisers.
     *     @type int $width
     *           The width and the height in pixels of the ad. Setting these is optional.
     *           However, these must be set if the bid BidRequest.AdSlot has more than one
     *           width and height or if BidRequest.Mobile.is_interstitial_request is true.
     *     @type int $height
     *     @type array<\BidResponse\Ad\AdSlot>|\Google\Protobuf\Internal\RepeatedField $adslot
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $impression_tracking_url
     *           The URLs to call when the impression is rendered. This is supported for
     *           all inventory types and all formats.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $click_tracking_urls
     *           The URLs to call when the user clicks on the ad. Currently supported only
     *           for native ads and Programmatic Guaranteed deals with publisher-
     *           managed creatives. In the publisher managed case, these click trackers
     *           will be sent to the bidder server to server. In all other cases, these
     *           will be sent from the user's device. For more information on
     *           publisher-managed creatives, see
     *           https://support.google.com/admanager/answer/9243220.
     *     @type string $ad_choices_destination_url
     *           Link to ad preferences page. This is only supported for native ads.
     *           If present, a standard AdChoices icon is added to the native creative and
     *           linked to this URL.
     *     @type array<\BidResponse\Ad\ImpressionTrackingResource>|\Google\Protobuf\Internal\RepeatedField $impression_tracking_resource
     *           Resources to invoke when the impression is rendered. This is supported
     *           for native and banner formats only and explicitly allowed scripts
     *           only.
     *     @type \BidResponse\Ad\SdkRenderedAd $sdk_rendered_ad
     *     @type \BidResponse\Ad\SKAdNetworkResponse $skadn
     *     @type string $advertised_app_id
     *           ID of the advertised app (only for app promotion).
     *           On Android, this should be a bundle or package name such as
     *           com.foo.mygame. On iOS, it is a numeric ID.
     *           In addition to this field, set the app_promotion_type field below to take
     *           advantage of features specific to app promotion types.
     *     @type int $app_promotion_type
     *           Type of the app promotion corresponding to the advertised app specified
     *           in the advertised_app_id field above.
     *           If the advertised app is not specified, this field will be ignored.
     *           Setting advertised_app_id field without this field will be treated as if
     *           this field were set to OTHER.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RealtimeBidding::initOnce();
        parent::__construct($data);
    }

    /**
     * The event notification token is sent to AdX by bidders for
     * troubleshooting. AdX will include the token in real-time feedback for the
     * bid. The content of the token will not be logged by AdX. AdX will ignore
     * any token longer than 128 bytes.
     *
     * Generated from protobuf field <code>optional bytes event_notification_token = 25;</code>
     * @return string
     */
    public function getEventNotificationToken()
    {
        return isset($this->event_notification_token) ? $this->event_notification_token : '';
    }

    public function hasEventNotificationToken()
    {
        return isset($this->event_notification_token);
    }

    public function clearEventNotificationToken()
    {
        unset($this->event_notification_token);
    }

    /**
     * The event notification token is sent to AdX by bidders for
     * troubleshooting. AdX will include the token in real-time feedback for the
     * bid. The content of the token will not be logged by AdX. AdX will ignore
     * any token longer than 128 bytes.
     *
     * Generated from protobuf field <code>optional bytes event_notification_token = 25;</code>
     * @param string $var
     * @return $this
     */
    public function setEventNotificationToken($var)
    {
        GPBUtil::checkString($var, False);
        $this->event_notification_token = $var;

        return $this;
    }

    /**
     * A unique identifier chosen by you for the creative in this response.
     * This must always be set, must be limited to at most 64 bytes, and must be
     * a valid UTF8 string. Every buyer_creative_id you use must always be
     * associated with the same creative. This field is used to communicate
     * approval statuses when issues are found. Do not specify the same id for
     * different creatives, or all creatives will be disapproved if a problem
     * with a single creative is found. Do not specify different ids for the
     * same creative in different responses or no creatives will be served since
     * approval status is assigned on a per-id basis.
     *
     * Generated from protobuf field <code>optional string buyer_creative_id = 10;</code>
     * @return string
     */
    public function getBuyerCreativeId()
    {
        return isset($this->buyer_creative_id) ? $this->buyer_creative_id : '';
    }

    public function hasBuyerCreativeId()
    {
        return isset($this->buyer_creative_id);
    }

    public function clearBuyerCreativeId()
    {
        unset($this->buyer_creative_id);
    }

    /**
     * A unique identifier chosen by you for the creative in this response.
     * This must always be set, must be limited to at most 64 bytes, and must be
     * a valid UTF8 string. Every buyer_creative_id you use must always be
     * associated with the same creative. This field is used to communicate
     * approval statuses when issues are found. Do not specify the same id for
     * different creatives, or all creatives will be disapproved if a problem
     * with a single creative is found. Do not specify different ids for the
     * same creative in different responses or no creatives will be served since
     * approval status is assigned on a per-id basis.
     *
     * Generated from protobuf field <code>optional string buyer_creative_id = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setBuyerCreativeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->buyer_creative_id = $var;

        return $this;
    }

    /**
     * Only one of the following should be set:
     * 1) html_snippet, 2) video_url, 3) native_ad, or 4) sdk_rendered_ad.
     * The HTML snippet that will be placed on the web page to display the ad.
     * Use BidResponse.Ad.AdSlot.billing_id to indicate which billing id
     * this snippet is attributed to.
     *
     * Generated from protobuf field <code>optional string html_snippet = 1;</code>
     * @return string
     */
    public function getHtmlSnippet()
    {
        return isset($this->html_snippet) ? $this->html_snippet : '';
    }

    public function hasHtmlSnippet()
    {
        return isset($this->html_snippet);
    }

    public function clearHtmlSnippet()
    {
        unset($this->html_snippet);
    }

    /**
     * Only one of the following should be set:
     * 1) html_snippet, 2) video_url, 3) native_ad, or 4) sdk_rendered_ad.
     * The HTML snippet that will be placed on the web page to display the ad.
     * Use BidResponse.Ad.AdSlot.billing_id to indicate which billing id
     * this snippet is attributed to.
     *
     * Generated from protobuf field <code>optional string html_snippet = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHtmlSnippet($var)
    {
        GPBUtil::checkString($var, True);
        $this->html_snippet = $var;

        return $this;
    }

    /**
     * The URL to fetch a video ad. The URL should return an XML response that
     * conforms to the VAST 2.0 or 3.0 standard. Use
     * BidResponse.Ad.AdSlot.billing_id to indicate which billing id to
     * attribute this ad to. Only one of the following should be set:
     * html_snippet, video_url. Only set this field if the BidRequest is for an
     * in-video ad (BidRequest.video is present).
     *
     * Generated from protobuf field <code>optional string video_url = 9;</code>
     * @return string
     */
    public function getVideoUrl()
    {
        return isset($this->video_url) ? $this->video_url : '';
    }

    public function hasVideoUrl()
    {
        return isset($this->video_url);
    }

    public function clearVideoUrl()
    {
        unset($this->video_url);
    }

    /**
     * The URL to fetch a video ad. The URL should return an XML response that
     * conforms to the VAST 2.0 or 3.0 standard. Use
     * BidResponse.Ad.AdSlot.billing_id to indicate which billing id to
     * attribute this ad to. Only one of the following should be set:
     * html_snippet, video_url. Only set this field if the BidRequest is for an
     * in-video ad (BidRequest.video is present).
     *
     * Generated from protobuf field <code>optional string video_url = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setVideoUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->video_url = $var;

        return $this;
    }

    /**
     * The VAST document to be returned. This document should conform to the
     * VAST 2.0 or 3.0 standard. Use BidResponse.Ad.AdSlot.billing_id to
     * indicate which billing ID to attribute this ad to.
     * Only set this field if the BidRequest is for an in-video ad and the
     * response is VAST XML.
     *
     * Generated from protobuf field <code>optional string video_vast_xml = 24;</code>
     * @return string
     */
    public function getVideoVastXml()
    {
        return isset($this->video_vast_xml) ? $this->video_vast_xml : '';
    }

    public function hasVideoVastXml()
    {
        return isset($this->video_vast_xml);
    }

    public function clearVideoVastXml()
    {
        unset($this->video_vast_xml);
    }

    /**
     * The VAST document to be returned. This document should conform to the
     * VAST 2.0 or 3.0 standard. Use BidResponse.Ad.AdSlot.billing_id to
     * indicate which billing ID to attribute this ad to.
     * Only set this field if the BidRequest is for an in-video ad and the
     * response is VAST XML.
     *
     * Generated from protobuf field <code>optional string video_vast_xml = 24;</code>
     * @param string $var
     * @return $this
     */
    public function setVideoVastXml($var)
    {
        GPBUtil::checkString($var, True);
        $this->video_vast_xml = $var;

        return $this;
    }

    /**
     * The URL to fetch an AMPHTML ad. Only one of the following should be set:
     * html_snippet, video_url, amp_ad_url, native_ad.
     *
     * Generated from protobuf field <code>optional string amp_ad_url = 23;</code>
     * @return string
     */
    public function getAmpAdUrl()
    {
        return isset($this->amp_ad_url) ? $this->amp_ad_url : '';
    }

    public function hasAmpAdUrl()
    {
        return isset($this->amp_ad_url);
    }

    public function clearAmpAdUrl()
    {
        unset($this->amp_ad_url);
    }

    /**
     * The URL to fetch an AMPHTML ad. Only one of the following should be set:
     * html_snippet, video_url, amp_ad_url, native_ad.
     *
     * Generated from protobuf field <code>optional string amp_ad_url = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setAmpAdUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->amp_ad_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .BidResponse.Ad.NativeAd native_ad = 18;</code>
     * @return \BidResponse\Ad\NativeAd|null
     */
    public function getNativeAd()
    {
        return $this->native_ad;
    }

    public function hasNativeAd()
    {
        return isset($this->native_ad);
    }

    public function clearNativeAd()
    {
        unset($this->native_ad);
    }

    /**
     * Generated from protobuf field <code>optional .BidResponse.Ad.NativeAd native_ad = 18;</code>
     * @param \BidResponse\Ad\NativeAd $var
     * @return $this
     */
    public function setNativeAd($var)
    {
        GPBUtil::checkMessage($var, \BidResponse\Ad\NativeAd::class);
        $this->native_ad = $var;

        return $this;
    }

    /**
     * The set of destination URLs for the snippet. This includes the URLs that
     * the user will go to if they click on the displayed ad, and any URLs that
     * are visible in the rendered ad. Do not include intermediate calls to the
     * adserver that are unrelated to the inal landing page. A BidResponse that
     * returns a snippet or video ad but declares no click_through_url will be
     * discarded. Only set this field if html_snippet or video_url or native_ad
     * are set. This data is used as a destination URL declaration, for example
     * for post-filtering of publisher-blocked URLs or ad categorization.
     * For non-native ads, it is not used for click tracking or any
     * other ad functionality; it is only used as a destination URL
     * declaration.
     * For native ads, if NativeAd.click_link_url is not set, the first
     * value of click_through_url is used to direct the user to the landing
     * page. In addition, all values are used as destination
     * URL declarations (similar to the non-native case).
     *
     * Generated from protobuf field <code>repeated string click_through_url = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getClickThroughUrl()
    {
        return $this->click_through_url;
    }

    /**
     * The set of destination URLs for the snippet. This includes the URLs that
     * the user will go to if they click on the displayed ad, and any URLs that
     * are visible in the rendered ad. Do not include intermediate calls to the
     * adserver that are unrelated to the inal landing page. A BidResponse that
     * returns a snippet or video ad but declares no click_through_url will be
     * discarded. Only set this field if html_snippet or video_url or native_ad
     * are set. This data is used as a destination URL declaration, for example
     * for post-filtering of publisher-blocked URLs or ad categorization.
     * For non-native ads, it is not used for click tracking or any
     * other ad functionality; it is only used as a destination URL
     * declaration.
     * For native ads, if NativeAd.click_link_url is not set, the first
     * value of click_through_url is used to direct the user to the landing
     * page. In addition, all values are used as destination
     * URL declarations (similar to the non-native case).
     *
     * Generated from protobuf field <code>repeated string click_through_url = 4;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setClickThroughUrl($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->click_through_url = $arr;

        return $this;
    }

    /**
     * All vendor types for the ads that may be shown from this snippet. You
     * should only declare vendor ids listed in the vendors.txt file in the
     * technical documentation. We will check to ensure that the vendors you
     * declare are in the allowed_vendor_type list sent in the BidRequest for
     * AdX publishers.
     *
     * Generated from protobuf field <code>repeated int32 vendor_type = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVendorType()
    {
        return $this->vendor_type;
    }

    /**
     * All vendor types for the ads that may be shown from this snippet. You
     * should only declare vendor ids listed in the vendors.txt file in the
     * technical documentation. We will check to ensure that the vendors you
     * declare are in the allowed_vendor_type list sent in the BidRequest for
     * AdX publishers.
     *
     * Generated from protobuf field <code>repeated int32 vendor_type = 5;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVendorType($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->vendor_type = $arr;

        return $this;
    }

    /**
     * All attributes for the ads that may be shown from this snippet. See
     * buyer-declarable-creative-attributes.txt in the technical documentation
     * for a list of ids. We will check to ensure none of these attributes are
     * in the excluded_attribute list in the BidRequest.
     *
     * Generated from protobuf field <code>repeated int32 attribute = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttribute()
    {
        return $this->attribute;
    }

    /**
     * All attributes for the ads that may be shown from this snippet. See
     * buyer-declarable-creative-attributes.txt in the technical documentation
     * for a list of ids. We will check to ensure none of these attributes are
     * in the excluded_attribute list in the BidRequest.
     *
     * Generated from protobuf field <code>repeated int32 attribute = 6;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttribute($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->attribute = $arr;

        return $this;
    }

    /**
     * All sensitive categories for the ads that may be shown from this snippet.
     * See ad-sensitive-categories.txt in the technical documentation for a list
     * of ids. We will check to ensure none of these categories were in the
     * excluded_sensitive_category list in the BidRequest.
     *
     * Generated from protobuf field <code>repeated int32 category = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * All sensitive categories for the ads that may be shown from this snippet.
     * See ad-sensitive-categories.txt in the technical documentation for a list
     * of ids. We will check to ensure none of these categories were in the
     * excluded_sensitive_category list in the BidRequest.
     *
     * Generated from protobuf field <code>repeated int32 category = 7;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCategory($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->category = $arr;

        return $this;
    }

    /**
     * All restricted categories for the ads that may be shown from this
     * snippet. See ad-restricted-categories.txt in the technical documentation
     * for a list of ids. We will check to ensure these categories were listed
     * in the allowed_restricted_category list in the BidRequest. If you are
     * bidding with ads in restricted categories you MUST ALWAYS declare them
     * here.
     *
     * Generated from protobuf field <code>repeated int32 restricted_category = 17;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRestrictedCategory()
    {
        return $this->restricted_category;
    }

    /**
     * All restricted categories for the ads that may be shown from this
     * snippet. See ad-restricted-categories.txt in the technical documentation
     * for a list of ids. We will check to ensure these categories were listed
     * in the allowed_restricted_category list in the BidRequest. If you are
     * bidding with ads in restricted categories you MUST ALWAYS declare them
     * here.
     *
     * Generated from protobuf field <code>repeated int32 restricted_category = 17;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRestrictedCategory($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->restricted_category = $arr;

        return $this;
    }

    /**
     * All names of the ad's advertisers.
     *
     * Generated from protobuf field <code>repeated string advertiser_name = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAdvertiserName()
    {
        return $this->advertiser_name;
    }

    /**
     * All names of the ad's advertisers.
     *
     * Generated from protobuf field <code>repeated string advertiser_name = 11;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAdvertiserName($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->advertiser_name = $arr;

        return $this;
    }

    /**
     * The width and the height in pixels of the ad. Setting these is optional.
     * However, these must be set if the bid BidRequest.AdSlot has more than one
     * width and height or if BidRequest.Mobile.is_interstitial_request is true.
     *
     * Generated from protobuf field <code>optional int32 width = 14;</code>
     * @return int
     */
    public function getWidth()
    {
        return isset($this->width) ? $this->width : 0;
    }

    public function hasWidth()
    {
        return isset($this->width);
    }

    public function clearWidth()
    {
        unset($this->width);
    }

    /**
     * The width and the height in pixels of the ad. Setting these is optional.
     * However, these must be set if the bid BidRequest.AdSlot has more than one
     * width and height or if BidRequest.Mobile.is_interstitial_request is true.
     *
     * Generated from protobuf field <code>optional int32 width = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setWidth($var)
    {
        GPBUtil::checkInt32($var);
        $this->width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 height = 15;</code>
     * @return int
     */
    public function getHeight()
    {
        return isset($this->height) ? $this->height : 0;
    }

    public function hasHeight()
    {
        return isset($this->height);
    }

    public function clearHeight()
    {
        unset($this->height);
    }

    /**
     * Generated from protobuf field <code>optional int32 height = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .BidResponse.Ad.AdSlot adslot = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAdslot()
    {
        return $this->adslot;
    }

    /**
     * Generated from protobuf field <code>repeated .BidResponse.Ad.AdSlot adslot = 3;</code>
     * @param array<\BidResponse\Ad\AdSlot>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAdslot($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \BidResponse\Ad\AdSlot::class);
        $this->adslot = $arr;

        return $this;
    }

    /**
     * The URLs to call when the impression is rendered. This is supported for
     * all inventory types and all formats.
     *
     * Generated from protobuf field <code>repeated string impression_tracking_url = 19;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getImpressionTrackingUrl()
    {
        return $this->impression_tracking_url;
    }

    /**
     * The URLs to call when the impression is rendered. This is supported for
     * all inventory types and all formats.
     *
     * Generated from protobuf field <code>repeated string impression_tracking_url = 19;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setImpressionTrackingUrl($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->impression_tracking_url = $arr;

        return $this;
    }

    /**
     * The URLs to call when the user clicks on the ad. Currently supported only
     * for native ads and Programmatic Guaranteed deals with publisher-
     * managed creatives. In the publisher managed case, these click trackers
     * will be sent to the bidder server to server. In all other cases, these
     * will be sent from the user's device. For more information on
     * publisher-managed creatives, see
     * https://support.google.com/admanager/answer/9243220.
     *
     * Generated from protobuf field <code>repeated string click_tracking_urls = 30;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getClickTrackingUrls()
    {
        return $this->click_tracking_urls;
    }

    /**
     * The URLs to call when the user clicks on the ad. Currently supported only
     * for native ads and Programmatic Guaranteed deals with publisher-
     * managed creatives. In the publisher managed case, these click trackers
     * will be sent to the bidder server to server. In all other cases, these
     * will be sent from the user's device. For more information on
     * publisher-managed creatives, see
     * https://support.google.com/admanager/answer/9243220.
     *
     * Generated from protobuf field <code>repeated string click_tracking_urls = 30;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setClickTrackingUrls($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->click_tracking_urls = $arr;

        return $this;
    }

    /**
     * Link to ad preferences page. This is only supported for native ads.
     * If present, a standard AdChoices icon is added to the native creative and
     * linked to this URL.
     *
     * Generated from protobuf field <code>optional string ad_choices_destination_url = 21;</code>
     * @return string
     */
    public function getAdChoicesDestinationUrl()
    {
        return isset($this->ad_choices_destination_url) ? $this->ad_choices_destination_url : '';
    }

    public function hasAdChoicesDestinationUrl()
    {
        return isset($this->ad_choices_destination_url);
    }

    public function clearAdChoicesDestinationUrl()
    {
        unset($this->ad_choices_destination_url);
    }

    /**
     * Link to ad preferences page. This is only supported for native ads.
     * If present, a standard AdChoices icon is added to the native creative and
     * linked to this URL.
     *
     * Generated from protobuf field <code>optional string ad_choices_destination_url = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setAdChoicesDestinationUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->ad_choices_destination_url = $var;

        return $this;
    }

    /**
     * Resources to invoke when the impression is rendered. This is supported
     * for native and banner formats only and explicitly allowed scripts
     * only.
     *
     * Generated from protobuf field <code>repeated .BidResponse.Ad.ImpressionTrackingResource impression_tracking_resource = 26;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getImpressionTrackingResource()
    {
        return $this->impression_tracking_resource;
    }

    /**
     * Resources to invoke when the impression is rendered. This is supported
     * for native and banner formats only and explicitly allowed scripts
     * only.
     *
     * Generated from protobuf field <code>repeated .BidResponse.Ad.ImpressionTrackingResource impression_tracking_resource = 26;</code>
     * @param array<\BidResponse\Ad\ImpressionTrackingResource>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setImpressionTrackingResource($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \BidResponse\Ad\ImpressionTrackingResource::class);
        $this->impression_tracking_resource = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .BidResponse.Ad.SdkRenderedAd sdk_rendered_ad = 27;</code>
     * @return \BidResponse\Ad\SdkRenderedAd|null
     */
    public function getSdkRenderedAd()
    {
        return $this->sdk_rendered_ad;
    }

    public function hasSdkRenderedAd()
    {
        return isset($this->sdk_rendered_ad);
    }

    public function clearSdkRenderedAd()
    {
        unset($this->sdk_rendered_ad);
    }

    /**
     * Generated from protobuf field <code>optional .BidResponse.Ad.SdkRenderedAd sdk_rendered_ad = 27;</code>
     * @param \BidResponse\Ad\SdkRenderedAd $var
     * @return $this
     */
    public function setSdkRenderedAd($var)
    {
        GPBUtil::checkMessage($var, \BidResponse\Ad\SdkRenderedAd::class);
        $this->sdk_rendered_ad = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .BidResponse.Ad.SKAdNetworkResponse skadn = 29;</code>
     * @return \BidResponse\Ad\SKAdNetworkResponse|null
     */
    public function getSkadn()
    {
        return $this->skadn;
    }

    public function hasSkadn()
    {
        return isset($this->skadn);
    }

    public function clearSkadn()
    {
        unset($this->skadn);
    }

    /**
     * Generated from protobuf field <code>optional .BidResponse.Ad.SKAdNetworkResponse skadn = 29;</code>
     * @param \BidResponse\Ad\SKAdNetworkResponse $var
     * @return $this
     */
    public function setSkadn($var)
    {
        GPBUtil::checkMessage($var, \BidResponse\Ad\SKAdNetworkResponse::class);
        $this->skadn = $var;

        return $this;
    }

    /**
     * ID of the advertised app (only for app promotion).
     * On Android, this should be a bundle or package name such as
     * com.foo.mygame. On iOS, it is a numeric ID.
     * In addition to this field, set the app_promotion_type field below to take
     * advantage of features specific to app promotion types.
     *
     * Generated from protobuf field <code>optional string advertised_app_id = 32;</code>
     * @return string
     */
    public function getAdvertisedAppId()
    {
        return isset($this->advertised_app_id) ? $this->advertised_app_id : '';
    }

    public function hasAdvertisedAppId()
    {
        return isset($this->advertised_app_id);
    }

    public function clearAdvertisedAppId()
    {
        unset($this->advertised_app_id);
    }

    /**
     * ID of the advertised app (only for app promotion).
     * On Android, this should be a bundle or package name such as
     * com.foo.mygame. On iOS, it is a numeric ID.
     * In addition to this field, set the app_promotion_type field below to take
     * advantage of features specific to app promotion types.
     *
     * Generated from protobuf field <code>optional string advertised_app_id = 32;</code>
     * @param string $var
     * @return $this
     */
    public function setAdvertisedAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->advertised_app_id = $var;

        return $this;
    }

    /**
     * Type of the app promotion corresponding to the advertised app specified
     * in the advertised_app_id field above.
     * If the advertised app is not specified, this field will be ignored.
     * Setting advertised_app_id field without this field will be treated as if
     * this field were set to OTHER.
     *
     * Generated from protobuf field <code>optional .BidResponse.Ad.AppPromotionType app_promotion_type = 33;</code>
     * @return int
     */
    public function getAppPromotionType()
    {
        return isset($this->app_promotion_type) ? $this->app_promotion_type : 0;
    }

    public function hasAppPromotionType()
    {
        return isset($this->app_promotion_type);
    }

    public function clearAppPromotionType()
    {
        unset($this->app_promotion_type);
    }

    /**
     * Type of the app promotion corresponding to the advertised app specified
     * in the advertised_app_id field above.
     * If the advertised app is not specified, this field will be ignored.
     * Setting advertised_app_id field without this field will be treated as if
     * this field were set to OTHER.
     *
     * Generated from protobuf field <code>optional .BidResponse.Ad.AppPromotionType app_promotion_type = 33;</code>
     * @param int $var
     * @return $this
     */
    public function setAppPromotionType($var)
    {
        GPBUtil::checkEnum($var, \BidResponse\Ad\AppPromotionType::class);
        $this->app_promotion_type = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Ad::class, \BidResponse_Ad::class);

