<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest\AdSlot\NativeAdTemplate;

use UnexpectedValueException;

/**
 * Defines the bits used in required_fields and recommended_fields. There
 * is one bit for each of the fields in BidResponse.Ad.NativeAd
 *
 * Protobuf type <code>BidRequest.AdSlot.NativeAdTemplate.Fields</code>
 */
class Fields
{
    /**
     * Generated from protobuf enum <code>NO_FIELDS = 0;</code>
     */
    const NO_FIELDS = 0;
    /**
     * Generated from protobuf enum <code>HEADLINE = 1;</code>
     */
    const HEADLINE = 1;
    /**
     * Generated from protobuf enum <code>BODY = 2;</code>
     */
    const BODY = 2;
    /**
     * Generated from protobuf enum <code>CALL_TO_ACTION = 4;</code>
     */
    const CALL_TO_ACTION = 4;
    /**
     * Generated from protobuf enum <code>ADVERTISER = 8;</code>
     */
    const ADVERTISER = 8;
    /**
     * Generated from protobuf enum <code>IMAGE = 16;</code>
     */
    const IMAGE = 16;
    /**
     * Generated from protobuf enum <code>LOGO = 32;</code>
     */
    const LOGO = 32;
    /**
     * Generated from protobuf enum <code>APP_ICON = 64;</code>
     */
    const APP_ICON = 64;
    /**
     * Generated from protobuf enum <code>STAR_RATING = 128;</code>
     */
    const STAR_RATING = 128;
    /**
     * Generated from protobuf enum <code>PRICE = 256;</code>
     */
    const PRICE = 256;
    /**
     * Generated from protobuf enum <code>DEPRECATED_STORE = 512;</code>
     */
    const DEPRECATED_STORE = 512;
    /**
     * Generated from protobuf enum <code>VIDEO = 1024;</code>
     */
    const VIDEO = 1024;

    private static $valueToName = [
        self::NO_FIELDS => 'NO_FIELDS',
        self::HEADLINE => 'HEADLINE',
        self::BODY => 'BODY',
        self::CALL_TO_ACTION => 'CALL_TO_ACTION',
        self::ADVERTISER => 'ADVERTISER',
        self::IMAGE => 'IMAGE',
        self::LOGO => 'LOGO',
        self::APP_ICON => 'APP_ICON',
        self::STAR_RATING => 'STAR_RATING',
        self::PRICE => 'PRICE',
        self::DEPRECATED_STORE => 'DEPRECATED_STORE',
        self::VIDEO => 'VIDEO',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Fields::class, \BidRequest_AdSlot_NativeAdTemplate_Fields::class);

