<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest\AdSlot\NativeAdTemplate;

use UnexpectedValueException;

/**
 * Type of style layout for each native ad template.
 *
 * Protobuf type <code>BidRequest.AdSlot.NativeAdTemplate.LayoutType</code>
 */
class LayoutType
{
    /**
     * Generated from protobuf enum <code>PIXEL = 0;</code>
     */
    const PIXEL = 0;
    /**
     * Generated from protobuf enum <code>FLUID = 1;</code>
     */
    const FLUID = 1;

    private static $valueToName = [
        self::PIXEL => 'PIXEL',
        self::FLUID => 'FLUID',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(LayoutType::class, \BidRequest_AdSlot_NativeAdTemplate_LayoutType::class);

