<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest\Hyperlocal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A location on the Earth's surface.
 *
 * Generated from protobuf message <code>BidRequest.Hyperlocal.Point</code>
 */
class Point extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional float latitude = 1;</code>
     */
    protected $latitude = null;
    /**
     * Generated from protobuf field <code>optional float longitude = 2;</code>
     */
    protected $longitude = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $latitude
     *     @type float $longitude
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RealtimeBidding::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional float latitude = 1;</code>
     * @return float
     */
    public function getLatitude()
    {
        return isset($this->latitude) ? $this->latitude : 0.0;
    }

    public function hasLatitude()
    {
        return isset($this->latitude);
    }

    public function clearLatitude()
    {
        unset($this->latitude);
    }

    /**
     * Generated from protobuf field <code>optional float latitude = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setLatitude($var)
    {
        GPBUtil::checkFloat($var);
        $this->latitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional float longitude = 2;</code>
     * @return float
     */
    public function getLongitude()
    {
        return isset($this->longitude) ? $this->longitude : 0.0;
    }

    public function hasLongitude()
    {
        return isset($this->longitude);
    }

    public function clearLongitude()
    {
        unset($this->longitude);
    }

    /**
     * Generated from protobuf field <code>optional float longitude = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setLongitude($var)
    {
        GPBUtil::checkFloat($var);
        $this->longitude = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Point::class, \BidRequest_Hyperlocal_Point::class);

