<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest\AdSlot\AdUnitMapping;

use UnexpectedValueException;

/**
 * Possible ad unit formats that can be used for the mapping. Corresponds
 * to the adapter that will be used on the SDK.
 *
 * Protobuf type <code>BidRequest.AdSlot.AdUnitMapping.FormatType</code>
 */
class FormatType
{
    /**
     * Generated from protobuf enum <code>FORMAT_UNKNOWN = 0;</code>
     */
    const FORMAT_UNKNOWN = 0;
    /**
     * Display banner ads for web or mobile apps. For example, a 320x50
     * leaderboard slot. This includes out-stream video.
     *
     * Generated from protobuf enum <code>FORMAT_BANNER = 1;</code>
     */
    const FORMAT_BANNER = 1;
    /**
     * A full-screen ad to be displayed inside a mobile app.
     *
     * Generated from protobuf enum <code>FORMAT_INTERSTITIAL = 2;</code>
     */
    const FORMAT_INTERSTITIAL = 2;
    /**
     * Custom display or video ads for web or mobile apps that match the
     * user experience of the site or app in which they’re placed.
     *
     * Generated from protobuf enum <code>FORMAT_NATIVE = 3;</code>
     */
    const FORMAT_NATIVE = 3;
    /**
     * Video ads that appear before, during, or after video content
     * streams.
     *
     * Generated from protobuf enum <code>FORMAT_VIDEO_VAST = 4;</code>
     */
    const FORMAT_VIDEO_VAST = 4;
    /**
     * Video ads for mobile apps that allow users to voluntarily watch an
     * ad in exchange for an in-app reward.
     *
     * Generated from protobuf enum <code>FORMAT_REWARDED = 5;</code>
     */
    const FORMAT_REWARDED = 5;
    /**
     * Interstitial ads that allow users to watch an ad in exchange for
     * an in-app reward. Does not require opt-in.
     * https://support.google.com/admanager/answer/7386053
     *
     * Generated from protobuf enum <code>FORMAT_REWARDED_INTERSTITIAL = 6;</code>
     */
    const FORMAT_REWARDED_INTERSTITIAL = 6;
    /**
     * App open ads shows at app load screens. App open ads can be closed
     * at any time, and are designed to be shown when the users bring the
     * app to the foreground.
     *
     * Generated from protobuf enum <code>FORMAT_APP_OPEN = 7;</code>
     */
    const FORMAT_APP_OPEN = 7;

    private static $valueToName = [
        self::FORMAT_UNKNOWN => 'FORMAT_UNKNOWN',
        self::FORMAT_BANNER => 'FORMAT_BANNER',
        self::FORMAT_INTERSTITIAL => 'FORMAT_INTERSTITIAL',
        self::FORMAT_NATIVE => 'FORMAT_NATIVE',
        self::FORMAT_VIDEO_VAST => 'FORMAT_VIDEO_VAST',
        self::FORMAT_REWARDED => 'FORMAT_REWARDED',
        self::FORMAT_REWARDED_INTERSTITIAL => 'FORMAT_REWARDED_INTERSTITIAL',
        self::FORMAT_APP_OPEN => 'FORMAT_APP_OPEN',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(FormatType::class, \BidRequest_AdSlot_AdUnitMapping_FormatType::class);

