<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest\AdSlot\AdUnitMapping;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Key-value pair used to specify the inventory unit in the bidder's
 * namespace.
 *
 * Generated from protobuf message <code>BidRequest.AdSlot.AdUnitMapping.Keyval</code>
 */
class Keyval extends \Google\Protobuf\Internal\Message
{
    /**
     * The key is the name of the bidder's inventory unit identifier for the
     * SDK.
     *
     * Generated from protobuf field <code>optional string key = 1;</code>
     */
    protected $key = null;
    /**
     * The value of the bidder's inventory unit identifier for the given
     * format.
     *
     * Generated from protobuf field <code>optional string value = 2;</code>
     */
    protected $value = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key
     *           The key is the name of the bidder's inventory unit identifier for the
     *           SDK.
     *     @type string $value
     *           The value of the bidder's inventory unit identifier for the given
     *           format.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RealtimeBidding::initOnce();
        parent::__construct($data);
    }

    /**
     * The key is the name of the bidder's inventory unit identifier for the
     * SDK.
     *
     * Generated from protobuf field <code>optional string key = 1;</code>
     * @return string
     */
    public function getKey()
    {
        return isset($this->key) ? $this->key : '';
    }

    public function hasKey()
    {
        return isset($this->key);
    }

    public function clearKey()
    {
        unset($this->key);
    }

    /**
     * The key is the name of the bidder's inventory unit identifier for the
     * SDK.
     *
     * Generated from protobuf field <code>optional string key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * The value of the bidder's inventory unit identifier for the given
     * format.
     *
     * Generated from protobuf field <code>optional string value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return isset($this->value) ? $this->value : '';
    }

    public function hasValue()
    {
        return isset($this->value);
    }

    public function clearValue()
    {
        unset($this->value);
    }

    /**
     * The value of the bidder's inventory unit identifier for the given
     * format.
     *
     * Generated from protobuf field <code>optional string value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Keyval::class, \BidRequest_AdSlot_AdUnitMapping_Keyval::class);

