<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Coarse geolocation information approximated based on the IP address of the
 * device the ad request originated from.
 *
 * Generated from protobuf message <code>BidRequest.Hyperlocal</code>
 */
class Hyperlocal extends \Google\Protobuf\Internal\Message
{
    /**
     * The device can be at any point inside the geofence polygon defined by a
     * list of corners. Currently, the polygon is always a parallelogram with 4
     * corners.
     *
     * Generated from protobuf field <code>repeated .BidRequest.Hyperlocal.Point corners = 1;</code>
     */
    private $corners;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\BidRequest\Hyperlocal\Point>|\Google\Protobuf\Internal\RepeatedField $corners
     *           The device can be at any point inside the geofence polygon defined by a
     *           list of corners. Currently, the polygon is always a parallelogram with 4
     *           corners.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RealtimeBidding::initOnce();
        parent::__construct($data);
    }

    /**
     * The device can be at any point inside the geofence polygon defined by a
     * list of corners. Currently, the polygon is always a parallelogram with 4
     * corners.
     *
     * Generated from protobuf field <code>repeated .BidRequest.Hyperlocal.Point corners = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCorners()
    {
        return $this->corners;
    }

    /**
     * The device can be at any point inside the geofence polygon defined by a
     * list of corners. Currently, the polygon is always a parallelogram with 4
     * corners.
     *
     * Generated from protobuf field <code>repeated .BidRequest.Hyperlocal.Point corners = 1;</code>
     * @param array<\BidRequest\Hyperlocal\Point>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCorners($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \BidRequest\Hyperlocal\Point::class);
        $this->corners = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Hyperlocal::class, \BidRequest_Hyperlocal::class);

