<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Information about privacy treatments that apply to an ad opportunity
 * offered through this request.
 *
 * Generated from protobuf message <code>BidRequest.PrivacyTreatments</code>
 */
class PrivacyTreatments extends \Google\Protobuf\Internal\Message
{
    /**
     * Generalization that was applied to the user_agent and user_agent_data
     * fields, if any.
     *
     * Generated from protobuf field <code>optional .BidRequest.PrivacyTreatments.UserAgentGeneralization user_agent = 2;</code>
     */
    protected $user_agent = null;
    /**
     * Deprecated. This will be removed in January 2024.
     * Generalization that was applied to the user_agent_data field, if any.
     *
     * Generated from protobuf field <code>optional .BidRequest.PrivacyTreatments.UserAgentDataGeneralization user_agent_data = 3 [deprecated = true];</code>
     * @deprecated
     */
    protected $user_agent_data = null;
    /**
     * Generated from protobuf field <code>repeated .BidRequest.PrivacyTreatments.NonPersonalizedAdsReason non_personalized_ads_reason = 6 [packed = true];</code>
     */
    private $non_personalized_ads_reason;
    /**
     * True if publisher grants the permission to allow the bidder to use bid
     * request data to build user profiles for uses such as interest-based ads
     * and remarketing. To use this data to build user profiles, a bidder must
     * also win a given impression.
     * Learn more about data collection controls:
     * https://support.google.com/admanager/answer/11956152
     *
     * Generated from protobuf field <code>optional bool allow_user_data_collection = 7;</code>
     */
    protected $allow_user_data_collection = null;
    /**
     * Indicates the reason why access of local device storage during winning ad
     * rendering and measurement is restricted.
     *
     * Generated from protobuf field <code>optional .BidRequest.PrivacyTreatments.DeviceStorageRestrictionReason device_storage_restriction_reason = 8;</code>
     */
    protected $device_storage_restriction_reason = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $user_agent
     *           Generalization that was applied to the user_agent and user_agent_data
     *           fields, if any.
     *     @type int $user_agent_data
     *           Deprecated. This will be removed in January 2024.
     *           Generalization that was applied to the user_agent_data field, if any.
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $non_personalized_ads_reason
     *     @type bool $allow_user_data_collection
     *           True if publisher grants the permission to allow the bidder to use bid
     *           request data to build user profiles for uses such as interest-based ads
     *           and remarketing. To use this data to build user profiles, a bidder must
     *           also win a given impression.
     *           Learn more about data collection controls:
     *           https://support.google.com/admanager/answer/11956152
     *     @type int $device_storage_restriction_reason
     *           Indicates the reason why access of local device storage during winning ad
     *           rendering and measurement is restricted.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RealtimeBidding::initOnce();
        parent::__construct($data);
    }

    /**
     * Generalization that was applied to the user_agent and user_agent_data
     * fields, if any.
     *
     * Generated from protobuf field <code>optional .BidRequest.PrivacyTreatments.UserAgentGeneralization user_agent = 2;</code>
     * @return int
     */
    public function getUserAgent()
    {
        return isset($this->user_agent) ? $this->user_agent : 0;
    }

    public function hasUserAgent()
    {
        return isset($this->user_agent);
    }

    public function clearUserAgent()
    {
        unset($this->user_agent);
    }

    /**
     * Generalization that was applied to the user_agent and user_agent_data
     * fields, if any.
     *
     * Generated from protobuf field <code>optional .BidRequest.PrivacyTreatments.UserAgentGeneralization user_agent = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUserAgent($var)
    {
        GPBUtil::checkEnum($var, \BidRequest\PrivacyTreatments\UserAgentGeneralization::class);
        $this->user_agent = $var;

        return $this;
    }

    /**
     * Deprecated. This will be removed in January 2024.
     * Generalization that was applied to the user_agent_data field, if any.
     *
     * Generated from protobuf field <code>optional .BidRequest.PrivacyTreatments.UserAgentDataGeneralization user_agent_data = 3 [deprecated = true];</code>
     * @return int
     * @deprecated
     */
    public function getUserAgentData()
    {
        @trigger_error('user_agent_data is deprecated.', E_USER_DEPRECATED);
        return isset($this->user_agent_data) ? $this->user_agent_data : 0;
    }

    public function hasUserAgentData()
    {
        @trigger_error('user_agent_data is deprecated.', E_USER_DEPRECATED);
        return isset($this->user_agent_data);
    }

    public function clearUserAgentData()
    {
        @trigger_error('user_agent_data is deprecated.', E_USER_DEPRECATED);
        unset($this->user_agent_data);
    }

    /**
     * Deprecated. This will be removed in January 2024.
     * Generalization that was applied to the user_agent_data field, if any.
     *
     * Generated from protobuf field <code>optional .BidRequest.PrivacyTreatments.UserAgentDataGeneralization user_agent_data = 3 [deprecated = true];</code>
     * @param int $var
     * @return $this
     * @deprecated
     */
    public function setUserAgentData($var)
    {
        @trigger_error('user_agent_data is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkEnum($var, \BidRequest\PrivacyTreatments\UserAgentDataGeneralization::class);
        $this->user_agent_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .BidRequest.PrivacyTreatments.NonPersonalizedAdsReason non_personalized_ads_reason = 6 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNonPersonalizedAdsReason()
    {
        return $this->non_personalized_ads_reason;
    }

    /**
     * Generated from protobuf field <code>repeated .BidRequest.PrivacyTreatments.NonPersonalizedAdsReason non_personalized_ads_reason = 6 [packed = true];</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNonPersonalizedAdsReason($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \BidRequest\PrivacyTreatments\NonPersonalizedAdsReason::class);
        $this->non_personalized_ads_reason = $arr;

        return $this;
    }

    /**
     * True if publisher grants the permission to allow the bidder to use bid
     * request data to build user profiles for uses such as interest-based ads
     * and remarketing. To use this data to build user profiles, a bidder must
     * also win a given impression.
     * Learn more about data collection controls:
     * https://support.google.com/admanager/answer/11956152
     *
     * Generated from protobuf field <code>optional bool allow_user_data_collection = 7;</code>
     * @return bool
     */
    public function getAllowUserDataCollection()
    {
        return isset($this->allow_user_data_collection) ? $this->allow_user_data_collection : false;
    }

    public function hasAllowUserDataCollection()
    {
        return isset($this->allow_user_data_collection);
    }

    public function clearAllowUserDataCollection()
    {
        unset($this->allow_user_data_collection);
    }

    /**
     * True if publisher grants the permission to allow the bidder to use bid
     * request data to build user profiles for uses such as interest-based ads
     * and remarketing. To use this data to build user profiles, a bidder must
     * also win a given impression.
     * Learn more about data collection controls:
     * https://support.google.com/admanager/answer/11956152
     *
     * Generated from protobuf field <code>optional bool allow_user_data_collection = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setAllowUserDataCollection($var)
    {
        GPBUtil::checkBool($var);
        $this->allow_user_data_collection = $var;

        return $this;
    }

    /**
     * Indicates the reason why access of local device storage during winning ad
     * rendering and measurement is restricted.
     *
     * Generated from protobuf field <code>optional .BidRequest.PrivacyTreatments.DeviceStorageRestrictionReason device_storage_restriction_reason = 8;</code>
     * @return int
     */
    public function getDeviceStorageRestrictionReason()
    {
        return isset($this->device_storage_restriction_reason) ? $this->device_storage_restriction_reason : 0;
    }

    public function hasDeviceStorageRestrictionReason()
    {
        return isset($this->device_storage_restriction_reason);
    }

    public function clearDeviceStorageRestrictionReason()
    {
        unset($this->device_storage_restriction_reason);
    }

    /**
     * Indicates the reason why access of local device storage during winning ad
     * rendering and measurement is restricted.
     *
     * Generated from protobuf field <code>optional .BidRequest.PrivacyTreatments.DeviceStorageRestrictionReason device_storage_restriction_reason = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setDeviceStorageRestrictionReason($var)
    {
        GPBUtil::checkEnum($var, \BidRequest\PrivacyTreatments\DeviceStorageRestrictionReason::class);
        $this->device_storage_restriction_reason = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PrivacyTreatments::class, \BidRequest_PrivacyTreatments::class);

