<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Information about a browser window's user activation state. See
 * https://html.spec.whatwg.org/multipage/interaction.html#the-useractivation-interface
 *
 * Generated from protobuf message <code>BidRequest.UserActivation</code>
 */
class UserActivation extends \Google\Protobuf\Internal\Message
{
    /**
     * Indicates whether a user has completed an interaction since page load.
     *
     * Generated from protobuf field <code>optional bool has_been_active = 1;</code>
     */
    protected $has_been_active = null;
    /**
     * Indicates whether a user is currently interacting with the page.
     *
     * Generated from protobuf field <code>optional bool is_active = 2;</code>
     */
    protected $is_active = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $has_been_active
     *           Indicates whether a user has completed an interaction since page load.
     *     @type bool $is_active
     *           Indicates whether a user is currently interacting with the page.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RealtimeBidding::initOnce();
        parent::__construct($data);
    }

    /**
     * Indicates whether a user has completed an interaction since page load.
     *
     * Generated from protobuf field <code>optional bool has_been_active = 1;</code>
     * @return bool
     */
    public function getHasBeenActive()
    {
        return isset($this->has_been_active) ? $this->has_been_active : false;
    }

    public function hasHasBeenActive()
    {
        return isset($this->has_been_active);
    }

    public function clearHasBeenActive()
    {
        unset($this->has_been_active);
    }

    /**
     * Indicates whether a user has completed an interaction since page load.
     *
     * Generated from protobuf field <code>optional bool has_been_active = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setHasBeenActive($var)
    {
        GPBUtil::checkBool($var);
        $this->has_been_active = $var;

        return $this;
    }

    /**
     * Indicates whether a user is currently interacting with the page.
     *
     * Generated from protobuf field <code>optional bool is_active = 2;</code>
     * @return bool
     */
    public function getIsActive()
    {
        return isset($this->is_active) ? $this->is_active : false;
    }

    public function hasIsActive()
    {
        return isset($this->is_active);
    }

    public function clearIsActive()
    {
        unset($this->is_active);
    }

    /**
     * Indicates whether a user is currently interacting with the page.
     *
     * Generated from protobuf field <code>optional bool is_active = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsActive($var)
    {
        GPBUtil::checkBool($var);
        $this->is_active = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(UserActivation::class, \BidRequest_UserActivation::class);

