<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * This field is not populated by default. We recommend that bidders instead
 * store and look up list ids using either google_user_id or hosted_match_data
 * as keys.
 *
 * Generated from protobuf message <code>BidRequest.UserList</code>
 */
class UserList extends \Google\Protobuf\Internal\Message
{
    /**
     * The user list id.
     *
     * Generated from protobuf field <code>optional int64 id = 1;</code>
     */
    protected $id = null;
    /**
     * The time in seconds since the user was added to the list.
     *
     * Generated from protobuf field <code>optional int32 age_seconds = 2;</code>
     */
    protected $age_seconds = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           The user list id.
     *     @type int $age_seconds
     *           The time in seconds since the user was added to the list.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RealtimeBidding::initOnce();
        parent::__construct($data);
    }

    /**
     * The user list id.
     *
     * Generated from protobuf field <code>optional int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return isset($this->id) ? $this->id : 0;
    }

    public function hasId()
    {
        return isset($this->id);
    }

    public function clearId()
    {
        unset($this->id);
    }

    /**
     * The user list id.
     *
     * Generated from protobuf field <code>optional int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * The time in seconds since the user was added to the list.
     *
     * Generated from protobuf field <code>optional int32 age_seconds = 2;</code>
     * @return int
     */
    public function getAgeSeconds()
    {
        return isset($this->age_seconds) ? $this->age_seconds : 0;
    }

    public function hasAgeSeconds()
    {
        return isset($this->age_seconds);
    }

    public function clearAgeSeconds()
    {
        unset($this->age_seconds);
    }

    /**
     * The time in seconds since the user was added to the list.
     *
     * Generated from protobuf field <code>optional int32 age_seconds = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAgeSeconds($var)
    {
        GPBUtil::checkInt32($var);
        $this->age_seconds = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(UserList::class, \BidRequest_UserList::class);

