<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest\AdSlot\CreativeEnforcementSettings;

use UnexpectedValueException;

/**
 * Creative publisher blocks enforcement level that applies to this
 * request. Publisher blocks allow publishers to control which creatives
 * can be shown on their properties.
 * Deals may also override publisher blocks. Refer to adslot.
 * matching_ad_data.direct_deal.publisher_blocks_overridden field.
 *
 * Protobuf type <code>BidRequest.AdSlot.CreativeEnforcementSettings.PublisherBlocksEnforcement</code>
 */
class PublisherBlocksEnforcement
{
    /**
     * Generated from protobuf enum <code>PUBLISHER_BLOCKS_ENFORCEMENT_UNKNOWN = 0;</code>
     */
    const PUBLISHER_BLOCKS_ENFORCEMENT_UNKNOWN = 0;
    /**
     * The publisher's blocking controls are enforced on creatives
     * submitted. Publisher blocks enforcement settings are provided in the
     * following fields:
     * - publisher_settings_list_id
     * - excluded_sensitive_category
     * - allowed_restricted_category
     * - excluded_product_category
     * - allowed_vendor_type
     * - excluded_attribute
     *
     * Generated from protobuf enum <code>PUBLISHER_BLOCKS_ENFORCEMENT_APPLIES = 1;</code>
     */
    const PUBLISHER_BLOCKS_ENFORCEMENT_APPLIES = 1;
    /**
     * The publisher's blocking controls are not enforced on creatives
     * submitted.
     *
     * Generated from protobuf enum <code>PUBLISHER_BLOCKS_ENFORCEMENT_OVERRIDDEN = 2;</code>
     */
    const PUBLISHER_BLOCKS_ENFORCEMENT_OVERRIDDEN = 2;

    private static $valueToName = [
        self::PUBLISHER_BLOCKS_ENFORCEMENT_UNKNOWN => 'PUBLISHER_BLOCKS_ENFORCEMENT_UNKNOWN',
        self::PUBLISHER_BLOCKS_ENFORCEMENT_APPLIES => 'PUBLISHER_BLOCKS_ENFORCEMENT_APPLIES',
        self::PUBLISHER_BLOCKS_ENFORCEMENT_OVERRIDDEN => 'PUBLISHER_BLOCKS_ENFORCEMENT_OVERRIDDEN',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PublisherBlocksEnforcement::class, \BidRequest_AdSlot_CreativeEnforcementSettings_PublisherBlocksEnforcement::class);

