<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest\PrivacyTreatments;

use UnexpectedValueException;

/**
 * Specifies the reasons that ads returned in response to this request
 * should not be personalized.
 *
 * Protobuf type <code>BidRequest.PrivacyTreatments.NonPersonalizedAdsReason</code>
 */
class NonPersonalizedAdsReason
{
    /**
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * The publisher has declared that this request should serve
     * non-personalized ads independent of other signals.
     * https://support.google.com/admanager/answer/9005435#npa
     *
     * Generated from protobuf enum <code>PUBLISHER_DECLARED_NPA = 1;</code>
     */
    const PUBLISHER_DECLARED_NPA = 1;
    /**
     * The publisher has requested restricted data processing for this
     * request. https://support.google.com/authorizedbuyers/answer/11121285
     *
     * Generated from protobuf enum <code>RESTRICT_DATA_PROCESSING = 2;</code>
     */
    const RESTRICT_DATA_PROCESSING = 2;
    /**
     * The user has opted out of ads personalization.
     *
     * Generated from protobuf enum <code>USER_OPT_OUT = 3;</code>
     */
    const USER_OPT_OUT = 3;

    private static $valueToName = [
        self::UNKNOWN => 'UNKNOWN',
        self::PUBLISHER_DECLARED_NPA => 'PUBLISHER_DECLARED_NPA',
        self::RESTRICT_DATA_PROCESSING => 'RESTRICT_DATA_PROCESSING',
        self::USER_OPT_OUT => 'USER_OPT_OUT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(NonPersonalizedAdsReason::class, \BidRequest_PrivacyTreatments_NonPersonalizedAdsReason::class);

