<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest\PrivacyTreatments;

use UnexpectedValueException;

/**
 * Generalization that can be applied to the user_agent and user_agent_data
 * fields.
 *
 * Protobuf type <code>BidRequest.PrivacyTreatments.UserAgentGeneralization</code>
 */
class UserAgentGeneralization
{
    /**
     * The user_agent and user_agent_data fields are both provided in full.
     *
     * Generated from protobuf enum <code>USER_AGENT_FULL = 0;</code>
     */
    const USER_AGENT_FULL = 0;
    /**
     * The user_agent and user_agent_data fields are generalized, which can
     * include limiting browser and OS version information to major versions
     * only and other changes to protect user privacy.
     *
     * Generated from protobuf enum <code>USER_AGENT_COARSENED = 1;</code>
     */
    const USER_AGENT_COARSENED = 1;

    private static $valueToName = [
        self::USER_AGENT_FULL => 'USER_AGENT_FULL',
        self::USER_AGENT_COARSENED => 'USER_AGENT_COARSENED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(UserAgentGeneralization::class, \BidRequest_PrivacyTreatments_UserAgentGeneralization::class);

