<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest\PrivacyTreatments;

use UnexpectedValueException;

/**
 * Generalization that can be applied to the user_agent_data field.
 *
 * Protobuf type <code>BidRequest.PrivacyTreatments.UserAgentDataGeneralization</code>
 */
class UserAgentDataGeneralization
{
    /**
     * The user_agent_data field is provided in full.
     *
     * Generated from protobuf enum <code>USER_AGENT_DATA_FULL = 0;</code>
     */
    const USER_AGENT_DATA_FULL = 0;
    /**
     * The user_agent_data field is generalized, which can include limiting
     * browser and OS version information to major versions only and other
     * changes to protect user privacy.
     *
     * Generated from protobuf enum <code>USER_AGENT_DATA_COARSENED = 1;</code>
     */
    const USER_AGENT_DATA_COARSENED = 1;

    private static $valueToName = [
        self::USER_AGENT_DATA_FULL => 'USER_AGENT_DATA_FULL',
        self::USER_AGENT_DATA_COARSENED => 'USER_AGENT_DATA_COARSENED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(UserAgentDataGeneralization::class, \BidRequest_PrivacyTreatments_UserAgentDataGeneralization::class);

