<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
/**
 * This is the message that Google uses to request bids. A BidRequest
 * includes the ad slot from a single impression.
 *
 * Generated from protobuf message <code>BidRequest</code>
 */
class BidRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Unique request id generated by Google. This is 16 bytes long.
     *
     * Generated from protobuf field <code>bytes id = 2;</code>
     */
    protected $id = '';
    /**
     * -----------------------------------------------------------
     * This section lists information that we know about the user.
     * The first 3 bytes of the IP address in network byte order for IPv4, or the
     * first 6 bytes for IPv6. Note that the number and position of the bytes
     * included from IPv6 addresses may change later.
     *
     * Generated from protobuf field <code>optional bytes ip = 4;</code>
     */
    protected $ip = null;
    /**
     * Deprecated. This will be removed in March 2024.
     * When user_data_treatment is set, the user's cookie/id data is cleared from
     * the request and is not sent in callout.
     * The impacted fields are:
     *  * google_user_id
     *  * hosted_match_data
     *  * mobile.encrypted_advertising_id
     *  * mobile.encrypted_hashed_idfa
     *  * session_id
     *
     * Generated from protobuf field <code>repeated .BidRequest.UserDataTreatment user_data_treatment = 49 [deprecated = true];</code>
     * @deprecated
     */
    private $user_data_treatment;
    /**
     * The Google ID for the user. This field is the unpadded web-safe base64
     * encoded version of a binary cookie id. See the "Base 64 Encoding with URL
     * and Filename Safe Alphabet" section in RFC 3548 for encoding details. This
     * field may be the same as the Google ID returned by the cookie matching
     * service. Not set if there is one or more user_data_treatment value.
     *
     * Generated from protobuf field <code>optional string google_user_id = 21;</code>
     */
    protected $google_user_id = null;
    /**
     * The version number of the google_user_id. We may sometimes change the
     * mapping from cookie to google_user_id. In this case the version will be
     * incremented.
     *
     * Generated from protobuf field <code>optional uint32 cookie_version = 20;</code>
     */
    protected $cookie_version = null;
    /**
     * The time in seconds since the google_user_id was created.
     * This number may be quantized.
     *
     * Generated from protobuf field <code>optional int32 cookie_age_seconds = 31;</code>
     */
    protected $cookie_age_seconds = null;
    /**
     * Match data stored for this google_user_id through the cookie matching
     * service. If a match exists, then this field holds the decoded data that
     * was passed in the google_hm parameter.
     * Not set if there is one or more user_data_treatment value.
     *
     * Generated from protobuf field <code>optional bytes hosted_match_data = 37;</code>
     */
    protected $hosted_match_data = null;
    /**
     * Represents a short-lived user session on CTV/OTT devices,
     * with a maximum session duration of 6 hours.
     * The use of session_id is never allowed for ads personalization.
     * session_id may only be used for frequency capping, competitive exclusions
     * or related purposes.
     *
     * Generated from protobuf field <code>optional string session_id = 65;</code>
     */
    protected $session_id = null;
    /**
     * A pseudonymized identifier created and controlled by the publisher for use
     * in frequency capping, audience segmentation and targeting, and sequential
     * ad rotation. See https://support.google.com/admanager/answer/2880055.
     *
     * Generated from protobuf field <code>optional string publisher_provided_id = 79;</code>
     */
    protected $publisher_provided_id = null;
    /**
     * Generated from protobuf field <code>optional .BidRequest.PublisherFirstPartyId publisher_first_party_id = 85;</code>
     */
    protected $publisher_first_party_id = null;
    /**
     * A string that identifies the browser and type of device that sent the
     * request. Certain data may be redacted or replaced.
     *
     * Generated from protobuf field <code>optional string user_agent = 6;</code>
     */
    protected $user_agent = null;
    /**
     * Generated from protobuf field <code>optional .BidRequest.PrivacyTreatments privacy_treatments = 71;</code>
     */
    protected $privacy_treatments = null;
    /**
     * Data segments for Publisher Provided Signals:
     * https://support.google.com/admanager/answer/12451124
     *
     * Generated from protobuf field <code>repeated .BidRequest.SegmentData segment_data = 75;</code>
     */
    private $segment_data;
    /**
     * Structured user agent information. If both BidRequest.ua and
     * BidRequest.sua are present, BidRequest.sua should be considered the
     * more accurate representation of the device attributes. This is because
     * BidRequest.ua may contain a frozen or reduced user agent string.
     *
     * Generated from protobuf field <code>optional .BidRequest.UserAgent user_agent_data = 63;</code>
     */
    protected $user_agent_data = null;
    /**
     * The billing address country of the publisher. This may be different from
     * the detected country of the user in geo_criteria_id or the hosting country
     * of the website. For a complete list of country codes, refer to
     * https://developers.google.com/google-ads/api/data/codes-formats#country_codes
     *
     * Generated from protobuf field <code>optional string publisher_country = 55;</code>
     */
    protected $publisher_country = null;
    /**
     * The ID of the host publisher. When populated, indicates that the host
     * publisher participated in revenue sharing, and the ID can be used to
     * authorize ads.txt.
     *
     * Generated from protobuf field <code>optional string host_publisher_id = 73;</code>
     */
    protected $host_publisher_id = null;
    /**
     * The domain of the partner (of the site/app owner) with ownership
     * of some portion of ad inventory on the site/app. The partner's ads.txt or
     * app-ads.txt file will be hosted here. More detail at
     * http://iabtechlab.com/wp-content/uploads/2021/03/ctv-app-ads-explainer-guide.pdf
     *
     * Generated from protobuf field <code>optional string inventory_partner_domain = 72;</code>
     */
    protected $inventory_partner_domain = null;
    /**
     * Location of the end user. Uses a subset of the codes used in the Google
     * Ads API. See the geo-table.csv table in the technical documentation for a
     * list of IDs. The geo_criteria_id field replaces the deprecated country,
     * region, city, and metro fields.
     * It is recommended that BidRequest.geo be used instead of this field.
     * See Geotargeting Guide:
     * https://developers.google.com/authorized-buyers/rtb/geotargeting
     *
     * Generated from protobuf field <code>optional int32 geo_criteria_id = 39;</code>
     */
    protected $geo_criteria_id = null;
    /**
     * Generated from protobuf field <code>optional .BidRequest.Geo geo = 62;</code>
     */
    protected $geo = null;
    /**
     * Deprecated. This field will be removed in Q3 2023. It is recommended that
     * BidRequest.geo.zip be used instead. See Geotargeting Guide:
     * https://developers.google.com/authorized-buyers/rtb/geotargeting
     * Detected postal code of the appropriate type for the country of the end
     * user (for example, zip code if the country is "US"). The postal_code_prefix
     * field is set when accuracy is too low to imply a full code, otherwise the
     * postal_code field is set.
     *
     * Generated from protobuf field <code>optional string postal_code = 33 [deprecated = true];</code>
     * @deprecated
     */
    protected $postal_code = null;
    /**
     * Deprecated. This field will be removed in Q3 2023. It is recommended that
     * BidRequest.geo.zip be used instead. See Geotargeting Guide:
     * https://developers.google.com/authorized-buyers/rtb/geotargeting
     *
     * Generated from protobuf field <code>optional string postal_code_prefix = 34 [deprecated = true];</code>
     * @deprecated
     */
    protected $postal_code_prefix = null;
    /**
     * Deprecated. This field will be removed in Q3 2023. It is recommended that
     * BidRequest.geo is used instead. See Geotargeting Guide:
     * https://developers.google.com/authorized-buyers/rtb/geotargeting
     * Encrypted hyperlocal targeting signals.
     *
     * Generated from protobuf field <code>optional bytes encrypted_hyperlocal_set = 40 [deprecated = true];</code>
     * @deprecated
     */
    protected $encrypted_hyperlocal_set = null;
    /**
     * Deprecated. This field will be removed in Q3 2023. It is recommended that
     * BidRequest.geo is used instead. See Geotargeting Guide:
     * https://developers.google.com/authorized-buyers/rtb/geotargeting
     * Unencrypted version of encrypted_hyperlocal_set. This field is only set
     * when using an SSL connection.
     *
     * Generated from protobuf field <code>optional .BidRequest.HyperlocalSet hyperlocal_set = 53 [deprecated = true];</code>
     * @deprecated
     */
    protected $hyperlocal_set = null;
    /**
     * Deprecated. This field will be removed in Q3 2023. It is recommended that
     * BidRequest.geo is used instead. See Geotargeting Guide:
     * https://developers.google.com/authorized-buyers/rtb/geotargeting
     * The offset of the user's time from GMT in minutes. For example, GMT+10 is
     * timezone_offset = 600.
     *
     * Generated from protobuf field <code>optional int32 timezone_offset = 25 [deprecated = true];</code>
     * @deprecated
     */
    protected $timezone_offset = null;
    /**
     * Generated from protobuf field <code>repeated .BidRequest.UserList user_list = 32;</code>
     */
    private $user_list;
    /**
     * -----------------------------------------------------------
     * This section lists information that we know about the web page or mobile
     * application where the impression originates.
     * The publisher ID as defined by the publisher code suffix of
     * the web property code. For instance, "pub-123" is the publisher code of web
     * property code "ca-pub-123" (ca- is the product specific prefix of the web
     * property).
     *
     * Generated from protobuf field <code>optional string publisher_id = 56;</code>
     */
    protected $publisher_id = null;
    /**
     * The seller network id. See seller-network-ids.txt file in the technical
     * documentation for a list of ids. This is only set if the site is not
     * anonymous and the publisher allows site targeting.
     *
     * Generated from protobuf field <code>optional int32 seller_network_id = 41;</code>
     */
    protected $seller_network_id = null;
    /**
     * Id for the partner that provides this inventory. This is only set when
     * seller_network_id is also set and further partner information beyond the
     * seller_network_id is also available. The value of the partner_id is not
     * meaningful beyond providing a stable identifier.
     *
     * Generated from protobuf field <code>optional fixed64 partner_id = 52;</code>
     */
    protected $partner_id = null;
    /**
     * The URL of the page with parameters removed. This is only set if the
     * publisher allows site targeting. This always starts with a protocol (either
     * http or https).
     *
     * Generated from protobuf field <code>optional string url = 11;</code>
     */
    protected $url = null;
    /**
     * Indicates that the request is using semi-transparent branding,
     * which means only a truncated version of the request URL will
     * be provided. This decision is made by the publisher, see
     * https://support.google.com/admanager/answer/4584891#urls for context.
     *
     * Generated from protobuf field <code>optional bool is_semi_transparent_request = 67;</code>
     */
    protected $is_semi_transparent_request = null;
    /**
     * Detected user languages, based on the language of the web page, the browser
     * settings, and other signals. The order is arbitrary. The codes are 2 or 5
     * characters and are documented at
     * https://developers.google.com/google-ads/api/data/codes-formats#languages
     *
     * Generated from protobuf field <code>repeated string detected_language = 12;</code>
     */
    private $detected_language;
    /**
     * Unordered list of detected content verticals. See the
     * publisher-verticals.txt file in the technical documentation for a list of
     * ids.
     *
     * Generated from protobuf field <code>repeated .BidRequest.Vertical detected_vertical = 13;</code>
     */
    private $detected_vertical;
    /**
     * List of detected content labels. See content-labels.txt file in the
     * technical documentation for a list of ids.
     *
     * Generated from protobuf field <code>repeated int32 detected_content_label = 26 [packed = true];</code>
     */
    private $detected_content_label;
    /**
     * The production quality of the content where an ad can be shown, as
     * determined by the publisher.
     *
     * Generated from protobuf field <code>optional .BidRequest.ProductionQuality production_quality = 80;</code>
     */
    protected $production_quality = null;
    /**
     * The rating of the content where an ad can be shown.
     *
     * Generated from protobuf field <code>optional .BidRequest.ContentRating content_rating = 84;</code>
     */
    protected $content_rating = null;
    /**
     * This represents a unique ID for the overall query. In the event
     * that there are multiple callouts for a query, all callout requests for that
     * query will contain the same google_query_id.
     *
     * Generated from protobuf field <code>optional string google_query_id = 59;</code>
     */
    protected $google_query_id = null;
    /**
     *[default = SECOND_PRICE];
     *
     * Generated from protobuf field <code>optional .BidRequest.AuctionType auction_type = 60;</code>
     */
    protected $auction_type = null;
    /**
     * Generated from protobuf field <code>optional .BidRequest.Device device = 54;</code>
     */
    protected $device = null;
    /**
     * Generated from protobuf field <code>repeated .BidRequest.KeyValue key_value = 38;</code>
     */
    private $key_value;
    /**
     * Generated from protobuf field <code>optional .BidRequest.Mobile mobile = 28;</code>
     */
    protected $mobile = null;
    /**
     * Generated from protobuf field <code>optional .BidRequest.Video video = 29;</code>
     */
    protected $video = null;
    /**
     * The publisher settings list id that applies to this page.
     * See the RTB Publisher Settings guide at
     * https://developers.google.com/authorized-buyers/rtb/pub-settings-guide
     * for details.
     *
     * Generated from protobuf field <code>optional fixed64 publisher_settings_list_id = 42;</code>
     */
    protected $publisher_settings_list_id = null;
    /**
     * Generated from protobuf field <code>optional .BidRequest.PublisherType publisher_type = 51;</code>
     */
    protected $publisher_type = null;
    /**
     * The visibility state of the web page containing the ad slots.
     * See https://www.w3.org/TR/page-visibility/.
     *
     * Generated from protobuf field <code>optional .BidRequest.VisibilityState page_visibility = 66;</code>
     */
    protected $page_visibility = null;
    /**
     * User activation information from the browser for the current request, if
     * the request is for a web page.
     *
     * Generated from protobuf field <code>optional .BidRequest.UserActivation user_activation = 76;</code>
     */
    protected $user_activation = null;
    /**
     * The type of browser navigation that led to the current page. Unset for
     * non-web ad requests.
     *
     * Generated from protobuf field <code>optional .BidRequest.NavigationType navigation_type = 77;</code>
     */
    protected $navigation_type = null;
    /**
     * Generated from protobuf field <code>repeated .BidRequest.AdSlot adslot = 14;</code>
     */
    private $adslot;
    /**
     * Generated from protobuf field <code>repeated .BidRequest.BidResponseFeedback bid_response_feedback = 44;</code>
     */
    private $bid_response_feedback;
    /**
     * How many milliseconds Google will wait for a response before ignoring it.
     *
     * Generated from protobuf field <code>optional int32 response_deadline_ms = 57;</code>
     */
    protected $response_deadline_ms = null;
    /**
     * -----------------------------------------------------------
     * Testing options.
     * If true, then this is a test request. Results will not be displayed to
     * users and you will not be billed for a response even if it wins the
     * auction. You should still do regular processing since the request may be
     * used to evaluate latencies or for other testing. During your initial
     * testing with Google traffic any response that you make will be filtered
     * out of the auction whether this option has a value of true or false.
     *
     * Generated from protobuf field <code>optional bool is_test = 15;</code>
     */
    protected $is_test = null;
    /**
     * If true, then this request is intended to measure network latency.
     * Return an empty BidResponse with only processing_time_ms set as quickly as
     * possible without executing any bidding logic.
     *
     * Generated from protobuf field <code>optional bool is_ping = 17;</code>
     */
    protected $is_ping = null;
    /**
     * If true, then the callout model predicted that you will not bid
     * on this request. We send a sampled percentage of such requests so that we
     * can automatically update the model when bidding patterns change.
     *
     * Generated from protobuf field <code>optional bool is_predicted_to_be_ignored = 45;</code>
     */
    protected $is_predicted_to_be_ignored = null;
    /**
     * Generated from protobuf field <code>optional .BidRequest.SupplyChain supply_chain = 69;</code>
     */
    protected $supply_chain = null;
    /**
     * Generated from protobuf field <code>optional .BidRequest.FrequencyCappingScope frequency_capping_scope = 70;</code>
     */
    protected $frequency_capping_scope = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           Unique request id generated by Google. This is 16 bytes long.
     *     @type string $ip
     *           -----------------------------------------------------------
     *           This section lists information that we know about the user.
     *           The first 3 bytes of the IP address in network byte order for IPv4, or the
     *           first 6 bytes for IPv6. Note that the number and position of the bytes
     *           included from IPv6 addresses may change later.
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $user_data_treatment
     *           Deprecated. This will be removed in March 2024.
     *           When user_data_treatment is set, the user's cookie/id data is cleared from
     *           the request and is not sent in callout.
     *           The impacted fields are:
     *            * google_user_id
     *            * hosted_match_data
     *            * mobile.encrypted_advertising_id
     *            * mobile.encrypted_hashed_idfa
     *            * session_id
     *     @type string $google_user_id
     *           The Google ID for the user. This field is the unpadded web-safe base64
     *           encoded version of a binary cookie id. See the "Base 64 Encoding with URL
     *           and Filename Safe Alphabet" section in RFC 3548 for encoding details. This
     *           field may be the same as the Google ID returned by the cookie matching
     *           service. Not set if there is one or more user_data_treatment value.
     *     @type int $cookie_version
     *           The version number of the google_user_id. We may sometimes change the
     *           mapping from cookie to google_user_id. In this case the version will be
     *           incremented.
     *     @type int $cookie_age_seconds
     *           The time in seconds since the google_user_id was created.
     *           This number may be quantized.
     *     @type string $hosted_match_data
     *           Match data stored for this google_user_id through the cookie matching
     *           service. If a match exists, then this field holds the decoded data that
     *           was passed in the google_hm parameter.
     *           Not set if there is one or more user_data_treatment value.
     *     @type string $session_id
     *           Represents a short-lived user session on CTV/OTT devices,
     *           with a maximum session duration of 6 hours.
     *           The use of session_id is never allowed for ads personalization.
     *           session_id may only be used for frequency capping, competitive exclusions
     *           or related purposes.
     *     @type string $publisher_provided_id
     *           A pseudonymized identifier created and controlled by the publisher for use
     *           in frequency capping, audience segmentation and targeting, and sequential
     *           ad rotation. See https://support.google.com/admanager/answer/2880055.
     *     @type \BidRequest\PublisherFirstPartyId $publisher_first_party_id
     *     @type string $user_agent
     *           A string that identifies the browser and type of device that sent the
     *           request. Certain data may be redacted or replaced.
     *     @type \BidRequest\PrivacyTreatments $privacy_treatments
     *     @type array<\BidRequest\SegmentData>|\Google\Protobuf\Internal\RepeatedField $segment_data
     *           Data segments for Publisher Provided Signals:
     *           https://support.google.com/admanager/answer/12451124
     *     @type \BidRequest\UserAgent $user_agent_data
     *           Structured user agent information. If both BidRequest.ua and
     *           BidRequest.sua are present, BidRequest.sua should be considered the
     *           more accurate representation of the device attributes. This is because
     *           BidRequest.ua may contain a frozen or reduced user agent string.
     *     @type string $publisher_country
     *           The billing address country of the publisher. This may be different from
     *           the detected country of the user in geo_criteria_id or the hosting country
     *           of the website. For a complete list of country codes, refer to
     *           https://developers.google.com/google-ads/api/data/codes-formats#country_codes
     *     @type string $host_publisher_id
     *           The ID of the host publisher. When populated, indicates that the host
     *           publisher participated in revenue sharing, and the ID can be used to
     *           authorize ads.txt.
     *     @type string $inventory_partner_domain
     *           The domain of the partner (of the site/app owner) with ownership
     *           of some portion of ad inventory on the site/app. The partner's ads.txt or
     *           app-ads.txt file will be hosted here. More detail at
     *           http://iabtechlab.com/wp-content/uploads/2021/03/ctv-app-ads-explainer-guide.pdf
     *     @type int $geo_criteria_id
     *           Location of the end user. Uses a subset of the codes used in the Google
     *           Ads API. See the geo-table.csv table in the technical documentation for a
     *           list of IDs. The geo_criteria_id field replaces the deprecated country,
     *           region, city, and metro fields.
     *           It is recommended that BidRequest.geo be used instead of this field.
     *           See Geotargeting Guide:
     *           https://developers.google.com/authorized-buyers/rtb/geotargeting
     *     @type \BidRequest\Geo $geo
     *     @type string $postal_code
     *           Deprecated. This field will be removed in Q3 2023. It is recommended that
     *           BidRequest.geo.zip be used instead. See Geotargeting Guide:
     *           https://developers.google.com/authorized-buyers/rtb/geotargeting
     *           Detected postal code of the appropriate type for the country of the end
     *           user (for example, zip code if the country is "US"). The postal_code_prefix
     *           field is set when accuracy is too low to imply a full code, otherwise the
     *           postal_code field is set.
     *     @type string $postal_code_prefix
     *           Deprecated. This field will be removed in Q3 2023. It is recommended that
     *           BidRequest.geo.zip be used instead. See Geotargeting Guide:
     *           https://developers.google.com/authorized-buyers/rtb/geotargeting
     *     @type string $encrypted_hyperlocal_set
     *           Deprecated. This field will be removed in Q3 2023. It is recommended that
     *           BidRequest.geo is used instead. See Geotargeting Guide:
     *           https://developers.google.com/authorized-buyers/rtb/geotargeting
     *           Encrypted hyperlocal targeting signals.
     *     @type \BidRequest\HyperlocalSet $hyperlocal_set
     *           Deprecated. This field will be removed in Q3 2023. It is recommended that
     *           BidRequest.geo is used instead. See Geotargeting Guide:
     *           https://developers.google.com/authorized-buyers/rtb/geotargeting
     *           Unencrypted version of encrypted_hyperlocal_set. This field is only set
     *           when using an SSL connection.
     *     @type int $timezone_offset
     *           Deprecated. This field will be removed in Q3 2023. It is recommended that
     *           BidRequest.geo is used instead. See Geotargeting Guide:
     *           https://developers.google.com/authorized-buyers/rtb/geotargeting
     *           The offset of the user's time from GMT in minutes. For example, GMT+10 is
     *           timezone_offset = 600.
     *     @type array<\BidRequest\UserList>|\Google\Protobuf\Internal\RepeatedField $user_list
     *     @type string $publisher_id
     *           -----------------------------------------------------------
     *           This section lists information that we know about the web page or mobile
     *           application where the impression originates.
     *           The publisher ID as defined by the publisher code suffix of
     *           the web property code. For instance, "pub-123" is the publisher code of web
     *           property code "ca-pub-123" (ca- is the product specific prefix of the web
     *           property).
     *     @type int $seller_network_id
     *           The seller network id. See seller-network-ids.txt file in the technical
     *           documentation for a list of ids. This is only set if the site is not
     *           anonymous and the publisher allows site targeting.
     *     @type int|string $partner_id
     *           Id for the partner that provides this inventory. This is only set when
     *           seller_network_id is also set and further partner information beyond the
     *           seller_network_id is also available. The value of the partner_id is not
     *           meaningful beyond providing a stable identifier.
     *     @type string $url
     *           The URL of the page with parameters removed. This is only set if the
     *           publisher allows site targeting. This always starts with a protocol (either
     *           http or https).
     *     @type bool $is_semi_transparent_request
     *           Indicates that the request is using semi-transparent branding,
     *           which means only a truncated version of the request URL will
     *           be provided. This decision is made by the publisher, see
     *           https://support.google.com/admanager/answer/4584891#urls for context.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $detected_language
     *           Detected user languages, based on the language of the web page, the browser
     *           settings, and other signals. The order is arbitrary. The codes are 2 or 5
     *           characters and are documented at
     *           https://developers.google.com/google-ads/api/data/codes-formats#languages
     *     @type array<\BidRequest\Vertical>|\Google\Protobuf\Internal\RepeatedField $detected_vertical
     *           Unordered list of detected content verticals. See the
     *           publisher-verticals.txt file in the technical documentation for a list of
     *           ids.
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $detected_content_label
     *           List of detected content labels. See content-labels.txt file in the
     *           technical documentation for a list of ids.
     *     @type int $production_quality
     *           The production quality of the content where an ad can be shown, as
     *           determined by the publisher.
     *     @type int $content_rating
     *           The rating of the content where an ad can be shown.
     *     @type string $google_query_id
     *           This represents a unique ID for the overall query. In the event
     *           that there are multiple callouts for a query, all callout requests for that
     *           query will contain the same google_query_id.
     *     @type int $auction_type
     *          [default = SECOND_PRICE];
     *     @type \BidRequest\Device $device
     *     @type array<\BidRequest\KeyValue>|\Google\Protobuf\Internal\RepeatedField $key_value
     *     @type \BidRequest\Mobile $mobile
     *     @type \BidRequest\Video $video
     *     @type int|string $publisher_settings_list_id
     *           The publisher settings list id that applies to this page.
     *           See the RTB Publisher Settings guide at
     *           https://developers.google.com/authorized-buyers/rtb/pub-settings-guide
     *           for details.
     *     @type int $publisher_type
     *     @type int $page_visibility
     *           The visibility state of the web page containing the ad slots.
     *           See https://www.w3.org/TR/page-visibility/.
     *     @type \BidRequest\UserActivation $user_activation
     *           User activation information from the browser for the current request, if
     *           the request is for a web page.
     *     @type int $navigation_type
     *           The type of browser navigation that led to the current page. Unset for
     *           non-web ad requests.
     *     @type array<\BidRequest\AdSlot>|\Google\Protobuf\Internal\RepeatedField $adslot
     *     @type array<\BidRequest\BidResponseFeedback>|\Google\Protobuf\Internal\RepeatedField $bid_response_feedback
     *     @type int $response_deadline_ms
     *           How many milliseconds Google will wait for a response before ignoring it.
     *     @type bool $is_test
     *           -----------------------------------------------------------
     *           Testing options.
     *           If true, then this is a test request. Results will not be displayed to
     *           users and you will not be billed for a response even if it wins the
     *           auction. You should still do regular processing since the request may be
     *           used to evaluate latencies or for other testing. During your initial
     *           testing with Google traffic any response that you make will be filtered
     *           out of the auction whether this option has a value of true or false.
     *     @type bool $is_ping
     *           If true, then this request is intended to measure network latency.
     *           Return an empty BidResponse with only processing_time_ms set as quickly as
     *           possible without executing any bidding logic.
     *     @type bool $is_predicted_to_be_ignored
     *           If true, then the callout model predicted that you will not bid
     *           on this request. We send a sampled percentage of such requests so that we
     *           can automatically update the model when bidding patterns change.
     *     @type \BidRequest\SupplyChain $supply_chain
     *     @type int $frequency_capping_scope
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RealtimeBidding::initOnce();
        parent::__construct($data);
    }

    /**
     * Unique request id generated by Google. This is 16 bytes long.
     *
     * Generated from protobuf field <code>bytes id = 2;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Unique request id generated by Google. This is 16 bytes long.
     *
     * Generated from protobuf field <code>bytes id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, False);
        $this->id = $var;

        return $this;
    }

    /**
     * -----------------------------------------------------------
     * This section lists information that we know about the user.
     * The first 3 bytes of the IP address in network byte order for IPv4, or the
     * first 6 bytes for IPv6. Note that the number and position of the bytes
     * included from IPv6 addresses may change later.
     *
     * Generated from protobuf field <code>optional bytes ip = 4;</code>
     * @return string
     */
    public function getIp()
    {
        return isset($this->ip) ? $this->ip : '';
    }

    public function hasIp()
    {
        return isset($this->ip);
    }

    public function clearIp()
    {
        unset($this->ip);
    }

    /**
     * -----------------------------------------------------------
     * This section lists information that we know about the user.
     * The first 3 bytes of the IP address in network byte order for IPv4, or the
     * first 6 bytes for IPv6. Note that the number and position of the bytes
     * included from IPv6 addresses may change later.
     *
     * Generated from protobuf field <code>optional bytes ip = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, False);
        $this->ip = $var;

        return $this;
    }

    /**
     * Deprecated. This will be removed in March 2024.
     * When user_data_treatment is set, the user's cookie/id data is cleared from
     * the request and is not sent in callout.
     * The impacted fields are:
     *  * google_user_id
     *  * hosted_match_data
     *  * mobile.encrypted_advertising_id
     *  * mobile.encrypted_hashed_idfa
     *  * session_id
     *
     * Generated from protobuf field <code>repeated .BidRequest.UserDataTreatment user_data_treatment = 49 [deprecated = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     * @deprecated
     */
    public function getUserDataTreatment()
    {
        @trigger_error('user_data_treatment is deprecated.', E_USER_DEPRECATED);
        return $this->user_data_treatment;
    }

    /**
     * Deprecated. This will be removed in March 2024.
     * When user_data_treatment is set, the user's cookie/id data is cleared from
     * the request and is not sent in callout.
     * The impacted fields are:
     *  * google_user_id
     *  * hosted_match_data
     *  * mobile.encrypted_advertising_id
     *  * mobile.encrypted_hashed_idfa
     *  * session_id
     *
     * Generated from protobuf field <code>repeated .BidRequest.UserDataTreatment user_data_treatment = 49 [deprecated = true];</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     * @deprecated
     */
    public function setUserDataTreatment($var)
    {
        @trigger_error('user_data_treatment is deprecated.', E_USER_DEPRECATED);
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \BidRequest\UserDataTreatment::class);
        $this->user_data_treatment = $arr;

        return $this;
    }

    /**
     * The Google ID for the user. This field is the unpadded web-safe base64
     * encoded version of a binary cookie id. See the "Base 64 Encoding with URL
     * and Filename Safe Alphabet" section in RFC 3548 for encoding details. This
     * field may be the same as the Google ID returned by the cookie matching
     * service. Not set if there is one or more user_data_treatment value.
     *
     * Generated from protobuf field <code>optional string google_user_id = 21;</code>
     * @return string
     */
    public function getGoogleUserId()
    {
        return isset($this->google_user_id) ? $this->google_user_id : '';
    }

    public function hasGoogleUserId()
    {
        return isset($this->google_user_id);
    }

    public function clearGoogleUserId()
    {
        unset($this->google_user_id);
    }

    /**
     * The Google ID for the user. This field is the unpadded web-safe base64
     * encoded version of a binary cookie id. See the "Base 64 Encoding with URL
     * and Filename Safe Alphabet" section in RFC 3548 for encoding details. This
     * field may be the same as the Google ID returned by the cookie matching
     * service. Not set if there is one or more user_data_treatment value.
     *
     * Generated from protobuf field <code>optional string google_user_id = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setGoogleUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->google_user_id = $var;

        return $this;
    }

    /**
     * The version number of the google_user_id. We may sometimes change the
     * mapping from cookie to google_user_id. In this case the version will be
     * incremented.
     *
     * Generated from protobuf field <code>optional uint32 cookie_version = 20;</code>
     * @return int
     */
    public function getCookieVersion()
    {
        return isset($this->cookie_version) ? $this->cookie_version : 0;
    }

    public function hasCookieVersion()
    {
        return isset($this->cookie_version);
    }

    public function clearCookieVersion()
    {
        unset($this->cookie_version);
    }

    /**
     * The version number of the google_user_id. We may sometimes change the
     * mapping from cookie to google_user_id. In this case the version will be
     * incremented.
     *
     * Generated from protobuf field <code>optional uint32 cookie_version = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setCookieVersion($var)
    {
        GPBUtil::checkUint32($var);
        $this->cookie_version = $var;

        return $this;
    }

    /**
     * The time in seconds since the google_user_id was created.
     * This number may be quantized.
     *
     * Generated from protobuf field <code>optional int32 cookie_age_seconds = 31;</code>
     * @return int
     */
    public function getCookieAgeSeconds()
    {
        return isset($this->cookie_age_seconds) ? $this->cookie_age_seconds : 0;
    }

    public function hasCookieAgeSeconds()
    {
        return isset($this->cookie_age_seconds);
    }

    public function clearCookieAgeSeconds()
    {
        unset($this->cookie_age_seconds);
    }

    /**
     * The time in seconds since the google_user_id was created.
     * This number may be quantized.
     *
     * Generated from protobuf field <code>optional int32 cookie_age_seconds = 31;</code>
     * @param int $var
     * @return $this
     */
    public function setCookieAgeSeconds($var)
    {
        GPBUtil::checkInt32($var);
        $this->cookie_age_seconds = $var;

        return $this;
    }

    /**
     * Match data stored for this google_user_id through the cookie matching
     * service. If a match exists, then this field holds the decoded data that
     * was passed in the google_hm parameter.
     * Not set if there is one or more user_data_treatment value.
     *
     * Generated from protobuf field <code>optional bytes hosted_match_data = 37;</code>
     * @return string
     */
    public function getHostedMatchData()
    {
        return isset($this->hosted_match_data) ? $this->hosted_match_data : '';
    }

    public function hasHostedMatchData()
    {
        return isset($this->hosted_match_data);
    }

    public function clearHostedMatchData()
    {
        unset($this->hosted_match_data);
    }

    /**
     * Match data stored for this google_user_id through the cookie matching
     * service. If a match exists, then this field holds the decoded data that
     * was passed in the google_hm parameter.
     * Not set if there is one or more user_data_treatment value.
     *
     * Generated from protobuf field <code>optional bytes hosted_match_data = 37;</code>
     * @param string $var
     * @return $this
     */
    public function setHostedMatchData($var)
    {
        GPBUtil::checkString($var, False);
        $this->hosted_match_data = $var;

        return $this;
    }

    /**
     * Represents a short-lived user session on CTV/OTT devices,
     * with a maximum session duration of 6 hours.
     * The use of session_id is never allowed for ads personalization.
     * session_id may only be used for frequency capping, competitive exclusions
     * or related purposes.
     *
     * Generated from protobuf field <code>optional string session_id = 65;</code>
     * @return string
     */
    public function getSessionId()
    {
        return isset($this->session_id) ? $this->session_id : '';
    }

    public function hasSessionId()
    {
        return isset($this->session_id);
    }

    public function clearSessionId()
    {
        unset($this->session_id);
    }

    /**
     * Represents a short-lived user session on CTV/OTT devices,
     * with a maximum session duration of 6 hours.
     * The use of session_id is never allowed for ads personalization.
     * session_id may only be used for frequency capping, competitive exclusions
     * or related purposes.
     *
     * Generated from protobuf field <code>optional string session_id = 65;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->session_id = $var;

        return $this;
    }

    /**
     * A pseudonymized identifier created and controlled by the publisher for use
     * in frequency capping, audience segmentation and targeting, and sequential
     * ad rotation. See https://support.google.com/admanager/answer/2880055.
     *
     * Generated from protobuf field <code>optional string publisher_provided_id = 79;</code>
     * @return string
     */
    public function getPublisherProvidedId()
    {
        return isset($this->publisher_provided_id) ? $this->publisher_provided_id : '';
    }

    public function hasPublisherProvidedId()
    {
        return isset($this->publisher_provided_id);
    }

    public function clearPublisherProvidedId()
    {
        unset($this->publisher_provided_id);
    }

    /**
     * A pseudonymized identifier created and controlled by the publisher for use
     * in frequency capping, audience segmentation and targeting, and sequential
     * ad rotation. See https://support.google.com/admanager/answer/2880055.
     *
     * Generated from protobuf field <code>optional string publisher_provided_id = 79;</code>
     * @param string $var
     * @return $this
     */
    public function setPublisherProvidedId($var)
    {
        GPBUtil::checkString($var, True);
        $this->publisher_provided_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .BidRequest.PublisherFirstPartyId publisher_first_party_id = 85;</code>
     * @return \BidRequest\PublisherFirstPartyId|null
     */
    public function getPublisherFirstPartyId()
    {
        return $this->publisher_first_party_id;
    }

    public function hasPublisherFirstPartyId()
    {
        return isset($this->publisher_first_party_id);
    }

    public function clearPublisherFirstPartyId()
    {
        unset($this->publisher_first_party_id);
    }

    /**
     * Generated from protobuf field <code>optional .BidRequest.PublisherFirstPartyId publisher_first_party_id = 85;</code>
     * @param \BidRequest\PublisherFirstPartyId $var
     * @return $this
     */
    public function setPublisherFirstPartyId($var)
    {
        GPBUtil::checkMessage($var, \BidRequest\PublisherFirstPartyId::class);
        $this->publisher_first_party_id = $var;

        return $this;
    }

    /**
     * A string that identifies the browser and type of device that sent the
     * request. Certain data may be redacted or replaced.
     *
     * Generated from protobuf field <code>optional string user_agent = 6;</code>
     * @return string
     */
    public function getUserAgent()
    {
        return isset($this->user_agent) ? $this->user_agent : '';
    }

    public function hasUserAgent()
    {
        return isset($this->user_agent);
    }

    public function clearUserAgent()
    {
        unset($this->user_agent);
    }

    /**
     * A string that identifies the browser and type of device that sent the
     * request. Certain data may be redacted or replaced.
     *
     * Generated from protobuf field <code>optional string user_agent = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setUserAgent($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_agent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .BidRequest.PrivacyTreatments privacy_treatments = 71;</code>
     * @return \BidRequest\PrivacyTreatments|null
     */
    public function getPrivacyTreatments()
    {
        return $this->privacy_treatments;
    }

    public function hasPrivacyTreatments()
    {
        return isset($this->privacy_treatments);
    }

    public function clearPrivacyTreatments()
    {
        unset($this->privacy_treatments);
    }

    /**
     * Generated from protobuf field <code>optional .BidRequest.PrivacyTreatments privacy_treatments = 71;</code>
     * @param \BidRequest\PrivacyTreatments $var
     * @return $this
     */
    public function setPrivacyTreatments($var)
    {
        GPBUtil::checkMessage($var, \BidRequest\PrivacyTreatments::class);
        $this->privacy_treatments = $var;

        return $this;
    }

    /**
     * Data segments for Publisher Provided Signals:
     * https://support.google.com/admanager/answer/12451124
     *
     * Generated from protobuf field <code>repeated .BidRequest.SegmentData segment_data = 75;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSegmentData()
    {
        return $this->segment_data;
    }

    /**
     * Data segments for Publisher Provided Signals:
     * https://support.google.com/admanager/answer/12451124
     *
     * Generated from protobuf field <code>repeated .BidRequest.SegmentData segment_data = 75;</code>
     * @param array<\BidRequest\SegmentData>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSegmentData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \BidRequest\SegmentData::class);
        $this->segment_data = $arr;

        return $this;
    }

    /**
     * Structured user agent information. If both BidRequest.ua and
     * BidRequest.sua are present, BidRequest.sua should be considered the
     * more accurate representation of the device attributes. This is because
     * BidRequest.ua may contain a frozen or reduced user agent string.
     *
     * Generated from protobuf field <code>optional .BidRequest.UserAgent user_agent_data = 63;</code>
     * @return \BidRequest\UserAgent|null
     */
    public function getUserAgentData()
    {
        return $this->user_agent_data;
    }

    public function hasUserAgentData()
    {
        return isset($this->user_agent_data);
    }

    public function clearUserAgentData()
    {
        unset($this->user_agent_data);
    }

    /**
     * Structured user agent information. If both BidRequest.ua and
     * BidRequest.sua are present, BidRequest.sua should be considered the
     * more accurate representation of the device attributes. This is because
     * BidRequest.ua may contain a frozen or reduced user agent string.
     *
     * Generated from protobuf field <code>optional .BidRequest.UserAgent user_agent_data = 63;</code>
     * @param \BidRequest\UserAgent $var
     * @return $this
     */
    public function setUserAgentData($var)
    {
        GPBUtil::checkMessage($var, \BidRequest\UserAgent::class);
        $this->user_agent_data = $var;

        return $this;
    }

    /**
     * The billing address country of the publisher. This may be different from
     * the detected country of the user in geo_criteria_id or the hosting country
     * of the website. For a complete list of country codes, refer to
     * https://developers.google.com/google-ads/api/data/codes-formats#country_codes
     *
     * Generated from protobuf field <code>optional string publisher_country = 55;</code>
     * @return string
     */
    public function getPublisherCountry()
    {
        return isset($this->publisher_country) ? $this->publisher_country : '';
    }

    public function hasPublisherCountry()
    {
        return isset($this->publisher_country);
    }

    public function clearPublisherCountry()
    {
        unset($this->publisher_country);
    }

    /**
     * The billing address country of the publisher. This may be different from
     * the detected country of the user in geo_criteria_id or the hosting country
     * of the website. For a complete list of country codes, refer to
     * https://developers.google.com/google-ads/api/data/codes-formats#country_codes
     *
     * Generated from protobuf field <code>optional string publisher_country = 55;</code>
     * @param string $var
     * @return $this
     */
    public function setPublisherCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->publisher_country = $var;

        return $this;
    }

    /**
     * The ID of the host publisher. When populated, indicates that the host
     * publisher participated in revenue sharing, and the ID can be used to
     * authorize ads.txt.
     *
     * Generated from protobuf field <code>optional string host_publisher_id = 73;</code>
     * @return string
     */
    public function getHostPublisherId()
    {
        return isset($this->host_publisher_id) ? $this->host_publisher_id : '';
    }

    public function hasHostPublisherId()
    {
        return isset($this->host_publisher_id);
    }

    public function clearHostPublisherId()
    {
        unset($this->host_publisher_id);
    }

    /**
     * The ID of the host publisher. When populated, indicates that the host
     * publisher participated in revenue sharing, and the ID can be used to
     * authorize ads.txt.
     *
     * Generated from protobuf field <code>optional string host_publisher_id = 73;</code>
     * @param string $var
     * @return $this
     */
    public function setHostPublisherId($var)
    {
        GPBUtil::checkString($var, True);
        $this->host_publisher_id = $var;

        return $this;
    }

    /**
     * The domain of the partner (of the site/app owner) with ownership
     * of some portion of ad inventory on the site/app. The partner's ads.txt or
     * app-ads.txt file will be hosted here. More detail at
     * http://iabtechlab.com/wp-content/uploads/2021/03/ctv-app-ads-explainer-guide.pdf
     *
     * Generated from protobuf field <code>optional string inventory_partner_domain = 72;</code>
     * @return string
     */
    public function getInventoryPartnerDomain()
    {
        return isset($this->inventory_partner_domain) ? $this->inventory_partner_domain : '';
    }

    public function hasInventoryPartnerDomain()
    {
        return isset($this->inventory_partner_domain);
    }

    public function clearInventoryPartnerDomain()
    {
        unset($this->inventory_partner_domain);
    }

    /**
     * The domain of the partner (of the site/app owner) with ownership
     * of some portion of ad inventory on the site/app. The partner's ads.txt or
     * app-ads.txt file will be hosted here. More detail at
     * http://iabtechlab.com/wp-content/uploads/2021/03/ctv-app-ads-explainer-guide.pdf
     *
     * Generated from protobuf field <code>optional string inventory_partner_domain = 72;</code>
     * @param string $var
     * @return $this
     */
    public function setInventoryPartnerDomain($var)
    {
        GPBUtil::checkString($var, True);
        $this->inventory_partner_domain = $var;

        return $this;
    }

    /**
     * Location of the end user. Uses a subset of the codes used in the Google
     * Ads API. See the geo-table.csv table in the technical documentation for a
     * list of IDs. The geo_criteria_id field replaces the deprecated country,
     * region, city, and metro fields.
     * It is recommended that BidRequest.geo be used instead of this field.
     * See Geotargeting Guide:
     * https://developers.google.com/authorized-buyers/rtb/geotargeting
     *
     * Generated from protobuf field <code>optional int32 geo_criteria_id = 39;</code>
     * @return int
     */
    public function getGeoCriteriaId()
    {
        return isset($this->geo_criteria_id) ? $this->geo_criteria_id : 0;
    }

    public function hasGeoCriteriaId()
    {
        return isset($this->geo_criteria_id);
    }

    public function clearGeoCriteriaId()
    {
        unset($this->geo_criteria_id);
    }

    /**
     * Location of the end user. Uses a subset of the codes used in the Google
     * Ads API. See the geo-table.csv table in the technical documentation for a
     * list of IDs. The geo_criteria_id field replaces the deprecated country,
     * region, city, and metro fields.
     * It is recommended that BidRequest.geo be used instead of this field.
     * See Geotargeting Guide:
     * https://developers.google.com/authorized-buyers/rtb/geotargeting
     *
     * Generated from protobuf field <code>optional int32 geo_criteria_id = 39;</code>
     * @param int $var
     * @return $this
     */
    public function setGeoCriteriaId($var)
    {
        GPBUtil::checkInt32($var);
        $this->geo_criteria_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .BidRequest.Geo geo = 62;</code>
     * @return \BidRequest\Geo|null
     */
    public function getGeo()
    {
        return $this->geo;
    }

    public function hasGeo()
    {
        return isset($this->geo);
    }

    public function clearGeo()
    {
        unset($this->geo);
    }

    /**
     * Generated from protobuf field <code>optional .BidRequest.Geo geo = 62;</code>
     * @param \BidRequest\Geo $var
     * @return $this
     */
    public function setGeo($var)
    {
        GPBUtil::checkMessage($var, \BidRequest\Geo::class);
        $this->geo = $var;

        return $this;
    }

    /**
     * Deprecated. This field will be removed in Q3 2023. It is recommended that
     * BidRequest.geo.zip be used instead. See Geotargeting Guide:
     * https://developers.google.com/authorized-buyers/rtb/geotargeting
     * Detected postal code of the appropriate type for the country of the end
     * user (for example, zip code if the country is "US"). The postal_code_prefix
     * field is set when accuracy is too low to imply a full code, otherwise the
     * postal_code field is set.
     *
     * Generated from protobuf field <code>optional string postal_code = 33 [deprecated = true];</code>
     * @return string
     * @deprecated
     */
    public function getPostalCode()
    {
        @trigger_error('postal_code is deprecated.', E_USER_DEPRECATED);
        return isset($this->postal_code) ? $this->postal_code : '';
    }

    public function hasPostalCode()
    {
        @trigger_error('postal_code is deprecated.', E_USER_DEPRECATED);
        return isset($this->postal_code);
    }

    public function clearPostalCode()
    {
        @trigger_error('postal_code is deprecated.', E_USER_DEPRECATED);
        unset($this->postal_code);
    }

    /**
     * Deprecated. This field will be removed in Q3 2023. It is recommended that
     * BidRequest.geo.zip be used instead. See Geotargeting Guide:
     * https://developers.google.com/authorized-buyers/rtb/geotargeting
     * Detected postal code of the appropriate type for the country of the end
     * user (for example, zip code if the country is "US"). The postal_code_prefix
     * field is set when accuracy is too low to imply a full code, otherwise the
     * postal_code field is set.
     *
     * Generated from protobuf field <code>optional string postal_code = 33 [deprecated = true];</code>
     * @param string $var
     * @return $this
     * @deprecated
     */
    public function setPostalCode($var)
    {
        @trigger_error('postal_code is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkString($var, True);
        $this->postal_code = $var;

        return $this;
    }

    /**
     * Deprecated. This field will be removed in Q3 2023. It is recommended that
     * BidRequest.geo.zip be used instead. See Geotargeting Guide:
     * https://developers.google.com/authorized-buyers/rtb/geotargeting
     *
     * Generated from protobuf field <code>optional string postal_code_prefix = 34 [deprecated = true];</code>
     * @return string
     * @deprecated
     */
    public function getPostalCodePrefix()
    {
        @trigger_error('postal_code_prefix is deprecated.', E_USER_DEPRECATED);
        return isset($this->postal_code_prefix) ? $this->postal_code_prefix : '';
    }

    public function hasPostalCodePrefix()
    {
        @trigger_error('postal_code_prefix is deprecated.', E_USER_DEPRECATED);
        return isset($this->postal_code_prefix);
    }

    public function clearPostalCodePrefix()
    {
        @trigger_error('postal_code_prefix is deprecated.', E_USER_DEPRECATED);
        unset($this->postal_code_prefix);
    }

    /**
     * Deprecated. This field will be removed in Q3 2023. It is recommended that
     * BidRequest.geo.zip be used instead. See Geotargeting Guide:
     * https://developers.google.com/authorized-buyers/rtb/geotargeting
     *
     * Generated from protobuf field <code>optional string postal_code_prefix = 34 [deprecated = true];</code>
     * @param string $var
     * @return $this
     * @deprecated
     */
    public function setPostalCodePrefix($var)
    {
        @trigger_error('postal_code_prefix is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkString($var, True);
        $this->postal_code_prefix = $var;

        return $this;
    }

    /**
     * Deprecated. This field will be removed in Q3 2023. It is recommended that
     * BidRequest.geo is used instead. See Geotargeting Guide:
     * https://developers.google.com/authorized-buyers/rtb/geotargeting
     * Encrypted hyperlocal targeting signals.
     *
     * Generated from protobuf field <code>optional bytes encrypted_hyperlocal_set = 40 [deprecated = true];</code>
     * @return string
     * @deprecated
     */
    public function getEncryptedHyperlocalSet()
    {
        @trigger_error('encrypted_hyperlocal_set is deprecated.', E_USER_DEPRECATED);
        return isset($this->encrypted_hyperlocal_set) ? $this->encrypted_hyperlocal_set : '';
    }

    public function hasEncryptedHyperlocalSet()
    {
        @trigger_error('encrypted_hyperlocal_set is deprecated.', E_USER_DEPRECATED);
        return isset($this->encrypted_hyperlocal_set);
    }

    public function clearEncryptedHyperlocalSet()
    {
        @trigger_error('encrypted_hyperlocal_set is deprecated.', E_USER_DEPRECATED);
        unset($this->encrypted_hyperlocal_set);
    }

    /**
     * Deprecated. This field will be removed in Q3 2023. It is recommended that
     * BidRequest.geo is used instead. See Geotargeting Guide:
     * https://developers.google.com/authorized-buyers/rtb/geotargeting
     * Encrypted hyperlocal targeting signals.
     *
     * Generated from protobuf field <code>optional bytes encrypted_hyperlocal_set = 40 [deprecated = true];</code>
     * @param string $var
     * @return $this
     * @deprecated
     */
    public function setEncryptedHyperlocalSet($var)
    {
        @trigger_error('encrypted_hyperlocal_set is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkString($var, False);
        $this->encrypted_hyperlocal_set = $var;

        return $this;
    }

    /**
     * Deprecated. This field will be removed in Q3 2023. It is recommended that
     * BidRequest.geo is used instead. See Geotargeting Guide:
     * https://developers.google.com/authorized-buyers/rtb/geotargeting
     * Unencrypted version of encrypted_hyperlocal_set. This field is only set
     * when using an SSL connection.
     *
     * Generated from protobuf field <code>optional .BidRequest.HyperlocalSet hyperlocal_set = 53 [deprecated = true];</code>
     * @return \BidRequest\HyperlocalSet|null
     * @deprecated
     */
    public function getHyperlocalSet()
    {
        @trigger_error('hyperlocal_set is deprecated.', E_USER_DEPRECATED);
        return $this->hyperlocal_set;
    }

    public function hasHyperlocalSet()
    {
        @trigger_error('hyperlocal_set is deprecated.', E_USER_DEPRECATED);
        return isset($this->hyperlocal_set);
    }

    public function clearHyperlocalSet()
    {
        @trigger_error('hyperlocal_set is deprecated.', E_USER_DEPRECATED);
        unset($this->hyperlocal_set);
    }

    /**
     * Deprecated. This field will be removed in Q3 2023. It is recommended that
     * BidRequest.geo is used instead. See Geotargeting Guide:
     * https://developers.google.com/authorized-buyers/rtb/geotargeting
     * Unencrypted version of encrypted_hyperlocal_set. This field is only set
     * when using an SSL connection.
     *
     * Generated from protobuf field <code>optional .BidRequest.HyperlocalSet hyperlocal_set = 53 [deprecated = true];</code>
     * @param \BidRequest\HyperlocalSet $var
     * @return $this
     * @deprecated
     */
    public function setHyperlocalSet($var)
    {
        @trigger_error('hyperlocal_set is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkMessage($var, \BidRequest\HyperlocalSet::class);
        $this->hyperlocal_set = $var;

        return $this;
    }

    /**
     * Deprecated. This field will be removed in Q3 2023. It is recommended that
     * BidRequest.geo is used instead. See Geotargeting Guide:
     * https://developers.google.com/authorized-buyers/rtb/geotargeting
     * The offset of the user's time from GMT in minutes. For example, GMT+10 is
     * timezone_offset = 600.
     *
     * Generated from protobuf field <code>optional int32 timezone_offset = 25 [deprecated = true];</code>
     * @return int
     * @deprecated
     */
    public function getTimezoneOffset()
    {
        @trigger_error('timezone_offset is deprecated.', E_USER_DEPRECATED);
        return isset($this->timezone_offset) ? $this->timezone_offset : 0;
    }

    public function hasTimezoneOffset()
    {
        @trigger_error('timezone_offset is deprecated.', E_USER_DEPRECATED);
        return isset($this->timezone_offset);
    }

    public function clearTimezoneOffset()
    {
        @trigger_error('timezone_offset is deprecated.', E_USER_DEPRECATED);
        unset($this->timezone_offset);
    }

    /**
     * Deprecated. This field will be removed in Q3 2023. It is recommended that
     * BidRequest.geo is used instead. See Geotargeting Guide:
     * https://developers.google.com/authorized-buyers/rtb/geotargeting
     * The offset of the user's time from GMT in minutes. For example, GMT+10 is
     * timezone_offset = 600.
     *
     * Generated from protobuf field <code>optional int32 timezone_offset = 25 [deprecated = true];</code>
     * @param int $var
     * @return $this
     * @deprecated
     */
    public function setTimezoneOffset($var)
    {
        @trigger_error('timezone_offset is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkInt32($var);
        $this->timezone_offset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .BidRequest.UserList user_list = 32;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserList()
    {
        return $this->user_list;
    }

    /**
     * Generated from protobuf field <code>repeated .BidRequest.UserList user_list = 32;</code>
     * @param array<\BidRequest\UserList>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \BidRequest\UserList::class);
        $this->user_list = $arr;

        return $this;
    }

    /**
     * -----------------------------------------------------------
     * This section lists information that we know about the web page or mobile
     * application where the impression originates.
     * The publisher ID as defined by the publisher code suffix of
     * the web property code. For instance, "pub-123" is the publisher code of web
     * property code "ca-pub-123" (ca- is the product specific prefix of the web
     * property).
     *
     * Generated from protobuf field <code>optional string publisher_id = 56;</code>
     * @return string
     */
    public function getPublisherId()
    {
        return isset($this->publisher_id) ? $this->publisher_id : '';
    }

    public function hasPublisherId()
    {
        return isset($this->publisher_id);
    }

    public function clearPublisherId()
    {
        unset($this->publisher_id);
    }

    /**
     * -----------------------------------------------------------
     * This section lists information that we know about the web page or mobile
     * application where the impression originates.
     * The publisher ID as defined by the publisher code suffix of
     * the web property code. For instance, "pub-123" is the publisher code of web
     * property code "ca-pub-123" (ca- is the product specific prefix of the web
     * property).
     *
     * Generated from protobuf field <code>optional string publisher_id = 56;</code>
     * @param string $var
     * @return $this
     */
    public function setPublisherId($var)
    {
        GPBUtil::checkString($var, True);
        $this->publisher_id = $var;

        return $this;
    }

    /**
     * The seller network id. See seller-network-ids.txt file in the technical
     * documentation for a list of ids. This is only set if the site is not
     * anonymous and the publisher allows site targeting.
     *
     * Generated from protobuf field <code>optional int32 seller_network_id = 41;</code>
     * @return int
     */
    public function getSellerNetworkId()
    {
        return isset($this->seller_network_id) ? $this->seller_network_id : 0;
    }

    public function hasSellerNetworkId()
    {
        return isset($this->seller_network_id);
    }

    public function clearSellerNetworkId()
    {
        unset($this->seller_network_id);
    }

    /**
     * The seller network id. See seller-network-ids.txt file in the technical
     * documentation for a list of ids. This is only set if the site is not
     * anonymous and the publisher allows site targeting.
     *
     * Generated from protobuf field <code>optional int32 seller_network_id = 41;</code>
     * @param int $var
     * @return $this
     */
    public function setSellerNetworkId($var)
    {
        GPBUtil::checkInt32($var);
        $this->seller_network_id = $var;

        return $this;
    }

    /**
     * Id for the partner that provides this inventory. This is only set when
     * seller_network_id is also set and further partner information beyond the
     * seller_network_id is also available. The value of the partner_id is not
     * meaningful beyond providing a stable identifier.
     *
     * Generated from protobuf field <code>optional fixed64 partner_id = 52;</code>
     * @return int|string
     */
    public function getPartnerId()
    {
        return isset($this->partner_id) ? $this->partner_id : 0;
    }

    public function hasPartnerId()
    {
        return isset($this->partner_id);
    }

    public function clearPartnerId()
    {
        unset($this->partner_id);
    }

    /**
     * Id for the partner that provides this inventory. This is only set when
     * seller_network_id is also set and further partner information beyond the
     * seller_network_id is also available. The value of the partner_id is not
     * meaningful beyond providing a stable identifier.
     *
     * Generated from protobuf field <code>optional fixed64 partner_id = 52;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPartnerId($var)
    {
        GPBUtil::checkUint64($var);
        $this->partner_id = $var;

        return $this;
    }

    /**
     * The URL of the page with parameters removed. This is only set if the
     * publisher allows site targeting. This always starts with a protocol (either
     * http or https).
     *
     * Generated from protobuf field <code>optional string url = 11;</code>
     * @return string
     */
    public function getUrl()
    {
        return isset($this->url) ? $this->url : '';
    }

    public function hasUrl()
    {
        return isset($this->url);
    }

    public function clearUrl()
    {
        unset($this->url);
    }

    /**
     * The URL of the page with parameters removed. This is only set if the
     * publisher allows site targeting. This always starts with a protocol (either
     * http or https).
     *
     * Generated from protobuf field <code>optional string url = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * Indicates that the request is using semi-transparent branding,
     * which means only a truncated version of the request URL will
     * be provided. This decision is made by the publisher, see
     * https://support.google.com/admanager/answer/4584891#urls for context.
     *
     * Generated from protobuf field <code>optional bool is_semi_transparent_request = 67;</code>
     * @return bool
     */
    public function getIsSemiTransparentRequest()
    {
        return isset($this->is_semi_transparent_request) ? $this->is_semi_transparent_request : false;
    }

    public function hasIsSemiTransparentRequest()
    {
        return isset($this->is_semi_transparent_request);
    }

    public function clearIsSemiTransparentRequest()
    {
        unset($this->is_semi_transparent_request);
    }

    /**
     * Indicates that the request is using semi-transparent branding,
     * which means only a truncated version of the request URL will
     * be provided. This decision is made by the publisher, see
     * https://support.google.com/admanager/answer/4584891#urls for context.
     *
     * Generated from protobuf field <code>optional bool is_semi_transparent_request = 67;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSemiTransparentRequest($var)
    {
        GPBUtil::checkBool($var);
        $this->is_semi_transparent_request = $var;

        return $this;
    }

    /**
     * Detected user languages, based on the language of the web page, the browser
     * settings, and other signals. The order is arbitrary. The codes are 2 or 5
     * characters and are documented at
     * https://developers.google.com/google-ads/api/data/codes-formats#languages
     *
     * Generated from protobuf field <code>repeated string detected_language = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDetectedLanguage()
    {
        return $this->detected_language;
    }

    /**
     * Detected user languages, based on the language of the web page, the browser
     * settings, and other signals. The order is arbitrary. The codes are 2 or 5
     * characters and are documented at
     * https://developers.google.com/google-ads/api/data/codes-formats#languages
     *
     * Generated from protobuf field <code>repeated string detected_language = 12;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDetectedLanguage($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->detected_language = $arr;

        return $this;
    }

    /**
     * Unordered list of detected content verticals. See the
     * publisher-verticals.txt file in the technical documentation for a list of
     * ids.
     *
     * Generated from protobuf field <code>repeated .BidRequest.Vertical detected_vertical = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDetectedVertical()
    {
        return $this->detected_vertical;
    }

    /**
     * Unordered list of detected content verticals. See the
     * publisher-verticals.txt file in the technical documentation for a list of
     * ids.
     *
     * Generated from protobuf field <code>repeated .BidRequest.Vertical detected_vertical = 13;</code>
     * @param array<\BidRequest\Vertical>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDetectedVertical($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \BidRequest\Vertical::class);
        $this->detected_vertical = $arr;

        return $this;
    }

    /**
     * List of detected content labels. See content-labels.txt file in the
     * technical documentation for a list of ids.
     *
     * Generated from protobuf field <code>repeated int32 detected_content_label = 26 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDetectedContentLabel()
    {
        return $this->detected_content_label;
    }

    /**
     * List of detected content labels. See content-labels.txt file in the
     * technical documentation for a list of ids.
     *
     * Generated from protobuf field <code>repeated int32 detected_content_label = 26 [packed = true];</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDetectedContentLabel($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->detected_content_label = $arr;

        return $this;
    }

    /**
     * The production quality of the content where an ad can be shown, as
     * determined by the publisher.
     *
     * Generated from protobuf field <code>optional .BidRequest.ProductionQuality production_quality = 80;</code>
     * @return int
     */
    public function getProductionQuality()
    {
        return isset($this->production_quality) ? $this->production_quality : 0;
    }

    public function hasProductionQuality()
    {
        return isset($this->production_quality);
    }

    public function clearProductionQuality()
    {
        unset($this->production_quality);
    }

    /**
     * The production quality of the content where an ad can be shown, as
     * determined by the publisher.
     *
     * Generated from protobuf field <code>optional .BidRequest.ProductionQuality production_quality = 80;</code>
     * @param int $var
     * @return $this
     */
    public function setProductionQuality($var)
    {
        GPBUtil::checkEnum($var, \BidRequest\ProductionQuality::class);
        $this->production_quality = $var;

        return $this;
    }

    /**
     * The rating of the content where an ad can be shown.
     *
     * Generated from protobuf field <code>optional .BidRequest.ContentRating content_rating = 84;</code>
     * @return int
     */
    public function getContentRating()
    {
        return isset($this->content_rating) ? $this->content_rating : 0;
    }

    public function hasContentRating()
    {
        return isset($this->content_rating);
    }

    public function clearContentRating()
    {
        unset($this->content_rating);
    }

    /**
     * The rating of the content where an ad can be shown.
     *
     * Generated from protobuf field <code>optional .BidRequest.ContentRating content_rating = 84;</code>
     * @param int $var
     * @return $this
     */
    public function setContentRating($var)
    {
        GPBUtil::checkEnum($var, \BidRequest\ContentRating::class);
        $this->content_rating = $var;

        return $this;
    }

    /**
     * This represents a unique ID for the overall query. In the event
     * that there are multiple callouts for a query, all callout requests for that
     * query will contain the same google_query_id.
     *
     * Generated from protobuf field <code>optional string google_query_id = 59;</code>
     * @return string
     */
    public function getGoogleQueryId()
    {
        return isset($this->google_query_id) ? $this->google_query_id : '';
    }

    public function hasGoogleQueryId()
    {
        return isset($this->google_query_id);
    }

    public function clearGoogleQueryId()
    {
        unset($this->google_query_id);
    }

    /**
     * This represents a unique ID for the overall query. In the event
     * that there are multiple callouts for a query, all callout requests for that
     * query will contain the same google_query_id.
     *
     * Generated from protobuf field <code>optional string google_query_id = 59;</code>
     * @param string $var
     * @return $this
     */
    public function setGoogleQueryId($var)
    {
        GPBUtil::checkString($var, True);
        $this->google_query_id = $var;

        return $this;
    }

    /**
     *[default = SECOND_PRICE];
     *
     * Generated from protobuf field <code>optional .BidRequest.AuctionType auction_type = 60;</code>
     * @return int
     */
    public function getAuctionType()
    {
        return isset($this->auction_type) ? $this->auction_type : 0;
    }

    public function hasAuctionType()
    {
        return isset($this->auction_type);
    }

    public function clearAuctionType()
    {
        unset($this->auction_type);
    }

    /**
     *[default = SECOND_PRICE];
     *
     * Generated from protobuf field <code>optional .BidRequest.AuctionType auction_type = 60;</code>
     * @param int $var
     * @return $this
     */
    public function setAuctionType($var)
    {
        GPBUtil::checkEnum($var, \BidRequest\AuctionType::class);
        $this->auction_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .BidRequest.Device device = 54;</code>
     * @return \BidRequest\Device|null
     */
    public function getDevice()
    {
        return $this->device;
    }

    public function hasDevice()
    {
        return isset($this->device);
    }

    public function clearDevice()
    {
        unset($this->device);
    }

    /**
     * Generated from protobuf field <code>optional .BidRequest.Device device = 54;</code>
     * @param \BidRequest\Device $var
     * @return $this
     */
    public function setDevice($var)
    {
        GPBUtil::checkMessage($var, \BidRequest\Device::class);
        $this->device = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .BidRequest.KeyValue key_value = 38;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKeyValue()
    {
        return $this->key_value;
    }

    /**
     * Generated from protobuf field <code>repeated .BidRequest.KeyValue key_value = 38;</code>
     * @param array<\BidRequest\KeyValue>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKeyValue($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \BidRequest\KeyValue::class);
        $this->key_value = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .BidRequest.Mobile mobile = 28;</code>
     * @return \BidRequest\Mobile|null
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    public function hasMobile()
    {
        return isset($this->mobile);
    }

    public function clearMobile()
    {
        unset($this->mobile);
    }

    /**
     * Generated from protobuf field <code>optional .BidRequest.Mobile mobile = 28;</code>
     * @param \BidRequest\Mobile $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkMessage($var, \BidRequest\Mobile::class);
        $this->mobile = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .BidRequest.Video video = 29;</code>
     * @return \BidRequest\Video|null
     */
    public function getVideo()
    {
        return $this->video;
    }

    public function hasVideo()
    {
        return isset($this->video);
    }

    public function clearVideo()
    {
        unset($this->video);
    }

    /**
     * Generated from protobuf field <code>optional .BidRequest.Video video = 29;</code>
     * @param \BidRequest\Video $var
     * @return $this
     */
    public function setVideo($var)
    {
        GPBUtil::checkMessage($var, \BidRequest\Video::class);
        $this->video = $var;

        return $this;
    }

    /**
     * The publisher settings list id that applies to this page.
     * See the RTB Publisher Settings guide at
     * https://developers.google.com/authorized-buyers/rtb/pub-settings-guide
     * for details.
     *
     * Generated from protobuf field <code>optional fixed64 publisher_settings_list_id = 42;</code>
     * @return int|string
     */
    public function getPublisherSettingsListId()
    {
        return isset($this->publisher_settings_list_id) ? $this->publisher_settings_list_id : 0;
    }

    public function hasPublisherSettingsListId()
    {
        return isset($this->publisher_settings_list_id);
    }

    public function clearPublisherSettingsListId()
    {
        unset($this->publisher_settings_list_id);
    }

    /**
     * The publisher settings list id that applies to this page.
     * See the RTB Publisher Settings guide at
     * https://developers.google.com/authorized-buyers/rtb/pub-settings-guide
     * for details.
     *
     * Generated from protobuf field <code>optional fixed64 publisher_settings_list_id = 42;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPublisherSettingsListId($var)
    {
        GPBUtil::checkUint64($var);
        $this->publisher_settings_list_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .BidRequest.PublisherType publisher_type = 51;</code>
     * @return int
     */
    public function getPublisherType()
    {
        return isset($this->publisher_type) ? $this->publisher_type : 0;
    }

    public function hasPublisherType()
    {
        return isset($this->publisher_type);
    }

    public function clearPublisherType()
    {
        unset($this->publisher_type);
    }

    /**
     * Generated from protobuf field <code>optional .BidRequest.PublisherType publisher_type = 51;</code>
     * @param int $var
     * @return $this
     */
    public function setPublisherType($var)
    {
        GPBUtil::checkEnum($var, \BidRequest\PublisherType::class);
        $this->publisher_type = $var;

        return $this;
    }

    /**
     * The visibility state of the web page containing the ad slots.
     * See https://www.w3.org/TR/page-visibility/.
     *
     * Generated from protobuf field <code>optional .BidRequest.VisibilityState page_visibility = 66;</code>
     * @return int
     */
    public function getPageVisibility()
    {
        return isset($this->page_visibility) ? $this->page_visibility : 0;
    }

    public function hasPageVisibility()
    {
        return isset($this->page_visibility);
    }

    public function clearPageVisibility()
    {
        unset($this->page_visibility);
    }

    /**
     * The visibility state of the web page containing the ad slots.
     * See https://www.w3.org/TR/page-visibility/.
     *
     * Generated from protobuf field <code>optional .BidRequest.VisibilityState page_visibility = 66;</code>
     * @param int $var
     * @return $this
     */
    public function setPageVisibility($var)
    {
        GPBUtil::checkEnum($var, \BidRequest\VisibilityState::class);
        $this->page_visibility = $var;

        return $this;
    }

    /**
     * User activation information from the browser for the current request, if
     * the request is for a web page.
     *
     * Generated from protobuf field <code>optional .BidRequest.UserActivation user_activation = 76;</code>
     * @return \BidRequest\UserActivation|null
     */
    public function getUserActivation()
    {
        return $this->user_activation;
    }

    public function hasUserActivation()
    {
        return isset($this->user_activation);
    }

    public function clearUserActivation()
    {
        unset($this->user_activation);
    }

    /**
     * User activation information from the browser for the current request, if
     * the request is for a web page.
     *
     * Generated from protobuf field <code>optional .BidRequest.UserActivation user_activation = 76;</code>
     * @param \BidRequest\UserActivation $var
     * @return $this
     */
    public function setUserActivation($var)
    {
        GPBUtil::checkMessage($var, \BidRequest\UserActivation::class);
        $this->user_activation = $var;

        return $this;
    }

    /**
     * The type of browser navigation that led to the current page. Unset for
     * non-web ad requests.
     *
     * Generated from protobuf field <code>optional .BidRequest.NavigationType navigation_type = 77;</code>
     * @return int
     */
    public function getNavigationType()
    {
        return isset($this->navigation_type) ? $this->navigation_type : 0;
    }

    public function hasNavigationType()
    {
        return isset($this->navigation_type);
    }

    public function clearNavigationType()
    {
        unset($this->navigation_type);
    }

    /**
     * The type of browser navigation that led to the current page. Unset for
     * non-web ad requests.
     *
     * Generated from protobuf field <code>optional .BidRequest.NavigationType navigation_type = 77;</code>
     * @param int $var
     * @return $this
     */
    public function setNavigationType($var)
    {
        GPBUtil::checkEnum($var, \BidRequest\NavigationType::class);
        $this->navigation_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .BidRequest.AdSlot adslot = 14;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAdslot()
    {
        return $this->adslot;
    }

    /**
     * Generated from protobuf field <code>repeated .BidRequest.AdSlot adslot = 14;</code>
     * @param array<\BidRequest\AdSlot>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAdslot($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \BidRequest\AdSlot::class);
        $this->adslot = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .BidRequest.BidResponseFeedback bid_response_feedback = 44;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBidResponseFeedback()
    {
        return $this->bid_response_feedback;
    }

    /**
     * Generated from protobuf field <code>repeated .BidRequest.BidResponseFeedback bid_response_feedback = 44;</code>
     * @param array<\BidRequest\BidResponseFeedback>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBidResponseFeedback($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \BidRequest\BidResponseFeedback::class);
        $this->bid_response_feedback = $arr;

        return $this;
    }

    /**
     * How many milliseconds Google will wait for a response before ignoring it.
     *
     * Generated from protobuf field <code>optional int32 response_deadline_ms = 57;</code>
     * @return int
     */
    public function getResponseDeadlineMs()
    {
        return isset($this->response_deadline_ms) ? $this->response_deadline_ms : 0;
    }

    public function hasResponseDeadlineMs()
    {
        return isset($this->response_deadline_ms);
    }

    public function clearResponseDeadlineMs()
    {
        unset($this->response_deadline_ms);
    }

    /**
     * How many milliseconds Google will wait for a response before ignoring it.
     *
     * Generated from protobuf field <code>optional int32 response_deadline_ms = 57;</code>
     * @param int $var
     * @return $this
     */
    public function setResponseDeadlineMs($var)
    {
        GPBUtil::checkInt32($var);
        $this->response_deadline_ms = $var;

        return $this;
    }

    /**
     * -----------------------------------------------------------
     * Testing options.
     * If true, then this is a test request. Results will not be displayed to
     * users and you will not be billed for a response even if it wins the
     * auction. You should still do regular processing since the request may be
     * used to evaluate latencies or for other testing. During your initial
     * testing with Google traffic any response that you make will be filtered
     * out of the auction whether this option has a value of true or false.
     *
     * Generated from protobuf field <code>optional bool is_test = 15;</code>
     * @return bool
     */
    public function getIsTest()
    {
        return isset($this->is_test) ? $this->is_test : false;
    }

    public function hasIsTest()
    {
        return isset($this->is_test);
    }

    public function clearIsTest()
    {
        unset($this->is_test);
    }

    /**
     * -----------------------------------------------------------
     * Testing options.
     * If true, then this is a test request. Results will not be displayed to
     * users and you will not be billed for a response even if it wins the
     * auction. You should still do regular processing since the request may be
     * used to evaluate latencies or for other testing. During your initial
     * testing with Google traffic any response that you make will be filtered
     * out of the auction whether this option has a value of true or false.
     *
     * Generated from protobuf field <code>optional bool is_test = 15;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsTest($var)
    {
        GPBUtil::checkBool($var);
        $this->is_test = $var;

        return $this;
    }

    /**
     * If true, then this request is intended to measure network latency.
     * Return an empty BidResponse with only processing_time_ms set as quickly as
     * possible without executing any bidding logic.
     *
     * Generated from protobuf field <code>optional bool is_ping = 17;</code>
     * @return bool
     */
    public function getIsPing()
    {
        return isset($this->is_ping) ? $this->is_ping : false;
    }

    public function hasIsPing()
    {
        return isset($this->is_ping);
    }

    public function clearIsPing()
    {
        unset($this->is_ping);
    }

    /**
     * If true, then this request is intended to measure network latency.
     * Return an empty BidResponse with only processing_time_ms set as quickly as
     * possible without executing any bidding logic.
     *
     * Generated from protobuf field <code>optional bool is_ping = 17;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsPing($var)
    {
        GPBUtil::checkBool($var);
        $this->is_ping = $var;

        return $this;
    }

    /**
     * If true, then the callout model predicted that you will not bid
     * on this request. We send a sampled percentage of such requests so that we
     * can automatically update the model when bidding patterns change.
     *
     * Generated from protobuf field <code>optional bool is_predicted_to_be_ignored = 45;</code>
     * @return bool
     */
    public function getIsPredictedToBeIgnored()
    {
        return isset($this->is_predicted_to_be_ignored) ? $this->is_predicted_to_be_ignored : false;
    }

    public function hasIsPredictedToBeIgnored()
    {
        return isset($this->is_predicted_to_be_ignored);
    }

    public function clearIsPredictedToBeIgnored()
    {
        unset($this->is_predicted_to_be_ignored);
    }

    /**
     * If true, then the callout model predicted that you will not bid
     * on this request. We send a sampled percentage of such requests so that we
     * can automatically update the model when bidding patterns change.
     *
     * Generated from protobuf field <code>optional bool is_predicted_to_be_ignored = 45;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsPredictedToBeIgnored($var)
    {
        GPBUtil::checkBool($var);
        $this->is_predicted_to_be_ignored = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .BidRequest.SupplyChain supply_chain = 69;</code>
     * @return \BidRequest\SupplyChain|null
     */
    public function getSupplyChain()
    {
        return $this->supply_chain;
    }

    public function hasSupplyChain()
    {
        return isset($this->supply_chain);
    }

    public function clearSupplyChain()
    {
        unset($this->supply_chain);
    }

    /**
     * Generated from protobuf field <code>optional .BidRequest.SupplyChain supply_chain = 69;</code>
     * @param \BidRequest\SupplyChain $var
     * @return $this
     */
    public function setSupplyChain($var)
    {
        GPBUtil::checkMessage($var, \BidRequest\SupplyChain::class);
        $this->supply_chain = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .BidRequest.FrequencyCappingScope frequency_capping_scope = 70;</code>
     * @return int
     */
    public function getFrequencyCappingScope()
    {
        return isset($this->frequency_capping_scope) ? $this->frequency_capping_scope : 0;
    }

    public function hasFrequencyCappingScope()
    {
        return isset($this->frequency_capping_scope);
    }

    public function clearFrequencyCappingScope()
    {
        unset($this->frequency_capping_scope);
    }

    /**
     * Generated from protobuf field <code>optional .BidRequest.FrequencyCappingScope frequency_capping_scope = 70;</code>
     * @param int $var
     * @return $this
     */
    public function setFrequencyCappingScope($var)
    {
        GPBUtil::checkEnum($var, \BidRequest\FrequencyCappingScope::class);
        $this->frequency_capping_scope = $var;

        return $this;
    }

}

