<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * This is the message that you return in response to a BidRequest. You may
 * specify zero or more ads. For each ad, you should provide an ad slot on
 * which the ad can run. An ad slot is identified by the AdSlot.id from the
 * BidRequest. If you do not want to bid, submit a response with no ads and
 * with only the processing_time_ms set.
 *
 * Generated from protobuf message <code>BidResponse</code>
 */
class BidResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .BidResponse.Ad ad = 2;</code>
     */
    private $ad;
    /**
     * If is_test was set in the BidRequest, then you may return debug information
     * as plain text in this field. Don't set this field under normal
     * conditions, or set it to values longer than 100 characters. You should only
     * use this field when asked to do so as part of troubleshooting particular
     * problems.
     *
     * Generated from protobuf field <code>optional string debug_string = 5;</code>
     */
    protected $debug_string = null;
    /**
     * Set this to the processing time in milliseconds from when you
     * received the request to when you returned the response.
     *
     * Generated from protobuf field <code>optional int32 processing_time_ms = 4;</code>
     */
    protected $processing_time_ms = null;
    /**
     * An optional, bidder-specified reason for not submitting a bid. This field
     * is equivalent to BidResponse.nbr in the OpenRTB protocol and uses the same
     * namespace of no-bid reason codes. See
     * https://developers.google.com/authorized-buyers/rtb/downloads/no-bid-reasons.txt
     * for the full set of no-bid reason codes.
     *
     * Generated from protobuf field <code>optional int32 no_bid_reason = 6;</code>
     */
    protected $no_bid_reason = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\BidResponse\Ad>|\Google\Protobuf\Internal\RepeatedField $ad
     *     @type string $debug_string
     *           If is_test was set in the BidRequest, then you may return debug information
     *           as plain text in this field. Don't set this field under normal
     *           conditions, or set it to values longer than 100 characters. You should only
     *           use this field when asked to do so as part of troubleshooting particular
     *           problems.
     *     @type int $processing_time_ms
     *           Set this to the processing time in milliseconds from when you
     *           received the request to when you returned the response.
     *     @type int $no_bid_reason
     *           An optional, bidder-specified reason for not submitting a bid. This field
     *           is equivalent to BidResponse.nbr in the OpenRTB protocol and uses the same
     *           namespace of no-bid reason codes. See
     *           https://developers.google.com/authorized-buyers/rtb/downloads/no-bid-reasons.txt
     *           for the full set of no-bid reason codes.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RealtimeBidding::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .BidResponse.Ad ad = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAd()
    {
        return $this->ad;
    }

    /**
     * Generated from protobuf field <code>repeated .BidResponse.Ad ad = 2;</code>
     * @param array<\BidResponse\Ad>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAd($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \BidResponse\Ad::class);
        $this->ad = $arr;

        return $this;
    }

    /**
     * If is_test was set in the BidRequest, then you may return debug information
     * as plain text in this field. Don't set this field under normal
     * conditions, or set it to values longer than 100 characters. You should only
     * use this field when asked to do so as part of troubleshooting particular
     * problems.
     *
     * Generated from protobuf field <code>optional string debug_string = 5;</code>
     * @return string
     */
    public function getDebugString()
    {
        return isset($this->debug_string) ? $this->debug_string : '';
    }

    public function hasDebugString()
    {
        return isset($this->debug_string);
    }

    public function clearDebugString()
    {
        unset($this->debug_string);
    }

    /**
     * If is_test was set in the BidRequest, then you may return debug information
     * as plain text in this field. Don't set this field under normal
     * conditions, or set it to values longer than 100 characters. You should only
     * use this field when asked to do so as part of troubleshooting particular
     * problems.
     *
     * Generated from protobuf field <code>optional string debug_string = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDebugString($var)
    {
        GPBUtil::checkString($var, True);
        $this->debug_string = $var;

        return $this;
    }

    /**
     * Set this to the processing time in milliseconds from when you
     * received the request to when you returned the response.
     *
     * Generated from protobuf field <code>optional int32 processing_time_ms = 4;</code>
     * @return int
     */
    public function getProcessingTimeMs()
    {
        return isset($this->processing_time_ms) ? $this->processing_time_ms : 0;
    }

    public function hasProcessingTimeMs()
    {
        return isset($this->processing_time_ms);
    }

    public function clearProcessingTimeMs()
    {
        unset($this->processing_time_ms);
    }

    /**
     * Set this to the processing time in milliseconds from when you
     * received the request to when you returned the response.
     *
     * Generated from protobuf field <code>optional int32 processing_time_ms = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setProcessingTimeMs($var)
    {
        GPBUtil::checkInt32($var);
        $this->processing_time_ms = $var;

        return $this;
    }

    /**
     * An optional, bidder-specified reason for not submitting a bid. This field
     * is equivalent to BidResponse.nbr in the OpenRTB protocol and uses the same
     * namespace of no-bid reason codes. See
     * https://developers.google.com/authorized-buyers/rtb/downloads/no-bid-reasons.txt
     * for the full set of no-bid reason codes.
     *
     * Generated from protobuf field <code>optional int32 no_bid_reason = 6;</code>
     * @return int
     */
    public function getNoBidReason()
    {
        return isset($this->no_bid_reason) ? $this->no_bid_reason : 0;
    }

    public function hasNoBidReason()
    {
        return isset($this->no_bid_reason);
    }

    public function clearNoBidReason()
    {
        unset($this->no_bid_reason);
    }

    /**
     * An optional, bidder-specified reason for not submitting a bid. This field
     * is equivalent to BidResponse.nbr in the OpenRTB protocol and uses the same
     * namespace of no-bid reason codes. See
     * https://developers.google.com/authorized-buyers/rtb/downloads/no-bid-reasons.txt
     * for the full set of no-bid reason codes.
     *
     * Generated from protobuf field <code>optional int32 no_bid_reason = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setNoBidReason($var)
    {
        GPBUtil::checkInt32($var);
        $this->no_bid_reason = $var;

        return $this;
    }

}

