<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidResponse\Ad\SKAdNetworkResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Google Mobile Ads SDK options for SKAdNetwork handling.
 *
 * Generated from protobuf message <code>BidResponse.Ad.SKAdNetworkResponse.SKAdNetworkOptions</code>
 */
class SKAdNetworkOptions extends \Google\Protobuf\Internal\Message
{
    /**
     * By default, SKAdNetwork attribution will only be initiated if the
     * click-through URL lands on the app store, either as a direct link to
     * the app store or as the final destination of a server-side redirect
     * chain. Enables GMA SDK to always initiate SKAdNetwork
     * attribution on-click regardless of the detected click's final
     * destination URL. Note that enabling this will launch the app store
     * even for clicks that are not meant to open the app store, for example
     * clicks on Ad Choices icon. For more info, see:
     * https://developers.google.com/authorized-buyers/rtb/skadnetwork
     *
     * Generated from protobuf field <code>optional bool always_open_appstore = 1;</code>
     */
    protected $always_open_appstore = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $always_open_appstore
     *           By default, SKAdNetwork attribution will only be initiated if the
     *           click-through URL lands on the app store, either as a direct link to
     *           the app store or as the final destination of a server-side redirect
     *           chain. Enables GMA SDK to always initiate SKAdNetwork
     *           attribution on-click regardless of the detected click's final
     *           destination URL. Note that enabling this will launch the app store
     *           even for clicks that are not meant to open the app store, for example
     *           clicks on Ad Choices icon. For more info, see:
     *           https://developers.google.com/authorized-buyers/rtb/skadnetwork
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RealtimeBidding::initOnce();
        parent::__construct($data);
    }

    /**
     * By default, SKAdNetwork attribution will only be initiated if the
     * click-through URL lands on the app store, either as a direct link to
     * the app store or as the final destination of a server-side redirect
     * chain. Enables GMA SDK to always initiate SKAdNetwork
     * attribution on-click regardless of the detected click's final
     * destination URL. Note that enabling this will launch the app store
     * even for clicks that are not meant to open the app store, for example
     * clicks on Ad Choices icon. For more info, see:
     * https://developers.google.com/authorized-buyers/rtb/skadnetwork
     *
     * Generated from protobuf field <code>optional bool always_open_appstore = 1;</code>
     * @return bool
     */
    public function getAlwaysOpenAppstore()
    {
        return isset($this->always_open_appstore) ? $this->always_open_appstore : false;
    }

    public function hasAlwaysOpenAppstore()
    {
        return isset($this->always_open_appstore);
    }

    public function clearAlwaysOpenAppstore()
    {
        unset($this->always_open_appstore);
    }

    /**
     * By default, SKAdNetwork attribution will only be initiated if the
     * click-through URL lands on the app store, either as a direct link to
     * the app store or as the final destination of a server-side redirect
     * chain. Enables GMA SDK to always initiate SKAdNetwork
     * attribution on-click regardless of the detected click's final
     * destination URL. Note that enabling this will launch the app store
     * even for clicks that are not meant to open the app store, for example
     * clicks on Ad Choices icon. For more info, see:
     * https://developers.google.com/authorized-buyers/rtb/skadnetwork
     *
     * Generated from protobuf field <code>optional bool always_open_appstore = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setAlwaysOpenAppstore($var)
    {
        GPBUtil::checkBool($var);
        $this->always_open_appstore = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(SKAdNetworkOptions::class, \BidResponse_Ad_SKAdNetworkResponse_SKAdNetworkOptions::class);

