<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidResponse\Ad\SKAdNetworkResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * These options indicate how to present SKOverlay recommending the
 * advertised app.
 * Supported by iOS 14 and later.
 * For more info visit:
 * https://developer.apple.com/documentation/storekit/skoverlay
 *
 * Generated from protobuf message <code>BidResponse.Ad.SKAdNetworkResponse.SKOverlay</code>
 */
class SKOverlay extends \Google\Protobuf\Internal\Message
{
    /**
     * Delay in seconds after the ad begins before presenting the overlay.
     * If this field is set to 0, the overlay will be shown immediately
     * after the ad begins. If this field is unset, the overlay will not
     * be shown for the ad.
     *
     * Generated from protobuf field <code>optional int32 delay_seconds = 1;</code>
     */
    protected $delay_seconds = null;
    /**
     * Delay in seconds after the endcard shows before presenting the
     * overlay. (This field only applies to rewarded or interstitial video
     * creatives.) If this field is set to 0, the overlay will be shown
     * immediately after the endcard shows. If this field is unset,
     * the overlay will not be shown for the endcard.
     * If both `delay_seconds` and `endcard_delay_seconds` are set,
     * the overlay will be automatically dismissed when the ad ends,
     * and shown again after the endcard shows.
     *
     * Generated from protobuf field <code>optional int32 endcard_delay_seconds = 2;</code>
     */
    protected $endcard_delay_seconds = null;
    /**
     * Whether this overlay can be dismissed by the user.
     *
     * Generated from protobuf field <code>optional bool dismissible = 3;</code>
     */
    protected $dismissible = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $delay_seconds
     *           Delay in seconds after the ad begins before presenting the overlay.
     *           If this field is set to 0, the overlay will be shown immediately
     *           after the ad begins. If this field is unset, the overlay will not
     *           be shown for the ad.
     *     @type int $endcard_delay_seconds
     *           Delay in seconds after the endcard shows before presenting the
     *           overlay. (This field only applies to rewarded or interstitial video
     *           creatives.) If this field is set to 0, the overlay will be shown
     *           immediately after the endcard shows. If this field is unset,
     *           the overlay will not be shown for the endcard.
     *           If both `delay_seconds` and `endcard_delay_seconds` are set,
     *           the overlay will be automatically dismissed when the ad ends,
     *           and shown again after the endcard shows.
     *     @type bool $dismissible
     *           Whether this overlay can be dismissed by the user.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RealtimeBidding::initOnce();
        parent::__construct($data);
    }

    /**
     * Delay in seconds after the ad begins before presenting the overlay.
     * If this field is set to 0, the overlay will be shown immediately
     * after the ad begins. If this field is unset, the overlay will not
     * be shown for the ad.
     *
     * Generated from protobuf field <code>optional int32 delay_seconds = 1;</code>
     * @return int
     */
    public function getDelaySeconds()
    {
        return isset($this->delay_seconds) ? $this->delay_seconds : 0;
    }

    public function hasDelaySeconds()
    {
        return isset($this->delay_seconds);
    }

    public function clearDelaySeconds()
    {
        unset($this->delay_seconds);
    }

    /**
     * Delay in seconds after the ad begins before presenting the overlay.
     * If this field is set to 0, the overlay will be shown immediately
     * after the ad begins. If this field is unset, the overlay will not
     * be shown for the ad.
     *
     * Generated from protobuf field <code>optional int32 delay_seconds = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDelaySeconds($var)
    {
        GPBUtil::checkInt32($var);
        $this->delay_seconds = $var;

        return $this;
    }

    /**
     * Delay in seconds after the endcard shows before presenting the
     * overlay. (This field only applies to rewarded or interstitial video
     * creatives.) If this field is set to 0, the overlay will be shown
     * immediately after the endcard shows. If this field is unset,
     * the overlay will not be shown for the endcard.
     * If both `delay_seconds` and `endcard_delay_seconds` are set,
     * the overlay will be automatically dismissed when the ad ends,
     * and shown again after the endcard shows.
     *
     * Generated from protobuf field <code>optional int32 endcard_delay_seconds = 2;</code>
     * @return int
     */
    public function getEndcardDelaySeconds()
    {
        return isset($this->endcard_delay_seconds) ? $this->endcard_delay_seconds : 0;
    }

    public function hasEndcardDelaySeconds()
    {
        return isset($this->endcard_delay_seconds);
    }

    public function clearEndcardDelaySeconds()
    {
        unset($this->endcard_delay_seconds);
    }

    /**
     * Delay in seconds after the endcard shows before presenting the
     * overlay. (This field only applies to rewarded or interstitial video
     * creatives.) If this field is set to 0, the overlay will be shown
     * immediately after the endcard shows. If this field is unset,
     * the overlay will not be shown for the endcard.
     * If both `delay_seconds` and `endcard_delay_seconds` are set,
     * the overlay will be automatically dismissed when the ad ends,
     * and shown again after the endcard shows.
     *
     * Generated from protobuf field <code>optional int32 endcard_delay_seconds = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setEndcardDelaySeconds($var)
    {
        GPBUtil::checkInt32($var);
        $this->endcard_delay_seconds = $var;

        return $this;
    }

    /**
     * Whether this overlay can be dismissed by the user.
     *
     * Generated from protobuf field <code>optional bool dismissible = 3;</code>
     * @return bool
     */
    public function getDismissible()
    {
        return isset($this->dismissible) ? $this->dismissible : false;
    }

    public function hasDismissible()
    {
        return isset($this->dismissible);
    }

    public function clearDismissible()
    {
        unset($this->dismissible);
    }

    /**
     * Whether this overlay can be dismissed by the user.
     *
     * Generated from protobuf field <code>optional bool dismissible = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setDismissible($var)
    {
        GPBUtil::checkBool($var);
        $this->dismissible = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(SKOverlay::class, \BidResponse_Ad_SKAdNetworkResponse_SKOverlay::class);

