<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest\SupplyChain;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>BidRequest.SupplyChain.SupplyChainNode</code>
 */
class SupplyChainNode extends \Google\Protobuf\Internal\Message
{
    /**
     * The canonical domain name of the SSP, Exchange, Header Wrapper, etc
     * system that bidders connect to. This may be the operational domain of
     * the system, if that is different than the parent corporate domain, to
     * facilitate WHOIS and reverse IP lookups to establish clear ownership of
     * the delegate system. This should be the same value as used to identify
     * sellers in an ads.txt file if one exists.
     *
     * Generated from protobuf field <code>optional string advertising_system_identifier = 1;</code>
     */
    protected $advertising_system_identifier = null;
    /**
     * The identifier associated with the seller or reseller account within
     * the advertising system. This must contain the same value used in
     * transactions, specifically the publisher_id field in the Google
     * protocol. Should be limited to 64 characters in length.
     *
     * Generated from protobuf field <code>optional string seller_identifier = 2;</code>
     */
    protected $seller_identifier = null;
    /**
     * Indicates whether this node will be involved in the flow of payment for
     * the inventory. When set to true, the advertising system in the
     * advertising_system_identifier field pays the seller in the
     * seller_identifier field, who is responsible for paying the previous
     * node in the chain. When set to false, this node is not involved in the
     * flow of payment for the inventory.
     *
     * Generated from protobuf field <code>optional bool handles_payment = 6;</code>
     */
    protected $handles_payment = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $advertising_system_identifier
     *           The canonical domain name of the SSP, Exchange, Header Wrapper, etc
     *           system that bidders connect to. This may be the operational domain of
     *           the system, if that is different than the parent corporate domain, to
     *           facilitate WHOIS and reverse IP lookups to establish clear ownership of
     *           the delegate system. This should be the same value as used to identify
     *           sellers in an ads.txt file if one exists.
     *     @type string $seller_identifier
     *           The identifier associated with the seller or reseller account within
     *           the advertising system. This must contain the same value used in
     *           transactions, specifically the publisher_id field in the Google
     *           protocol. Should be limited to 64 characters in length.
     *     @type bool $handles_payment
     *           Indicates whether this node will be involved in the flow of payment for
     *           the inventory. When set to true, the advertising system in the
     *           advertising_system_identifier field pays the seller in the
     *           seller_identifier field, who is responsible for paying the previous
     *           node in the chain. When set to false, this node is not involved in the
     *           flow of payment for the inventory.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RealtimeBidding::initOnce();
        parent::__construct($data);
    }

    /**
     * The canonical domain name of the SSP, Exchange, Header Wrapper, etc
     * system that bidders connect to. This may be the operational domain of
     * the system, if that is different than the parent corporate domain, to
     * facilitate WHOIS and reverse IP lookups to establish clear ownership of
     * the delegate system. This should be the same value as used to identify
     * sellers in an ads.txt file if one exists.
     *
     * Generated from protobuf field <code>optional string advertising_system_identifier = 1;</code>
     * @return string
     */
    public function getAdvertisingSystemIdentifier()
    {
        return isset($this->advertising_system_identifier) ? $this->advertising_system_identifier : '';
    }

    public function hasAdvertisingSystemIdentifier()
    {
        return isset($this->advertising_system_identifier);
    }

    public function clearAdvertisingSystemIdentifier()
    {
        unset($this->advertising_system_identifier);
    }

    /**
     * The canonical domain name of the SSP, Exchange, Header Wrapper, etc
     * system that bidders connect to. This may be the operational domain of
     * the system, if that is different than the parent corporate domain, to
     * facilitate WHOIS and reverse IP lookups to establish clear ownership of
     * the delegate system. This should be the same value as used to identify
     * sellers in an ads.txt file if one exists.
     *
     * Generated from protobuf field <code>optional string advertising_system_identifier = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAdvertisingSystemIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->advertising_system_identifier = $var;

        return $this;
    }

    /**
     * The identifier associated with the seller or reseller account within
     * the advertising system. This must contain the same value used in
     * transactions, specifically the publisher_id field in the Google
     * protocol. Should be limited to 64 characters in length.
     *
     * Generated from protobuf field <code>optional string seller_identifier = 2;</code>
     * @return string
     */
    public function getSellerIdentifier()
    {
        return isset($this->seller_identifier) ? $this->seller_identifier : '';
    }

    public function hasSellerIdentifier()
    {
        return isset($this->seller_identifier);
    }

    public function clearSellerIdentifier()
    {
        unset($this->seller_identifier);
    }

    /**
     * The identifier associated with the seller or reseller account within
     * the advertising system. This must contain the same value used in
     * transactions, specifically the publisher_id field in the Google
     * protocol. Should be limited to 64 characters in length.
     *
     * Generated from protobuf field <code>optional string seller_identifier = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSellerIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->seller_identifier = $var;

        return $this;
    }

    /**
     * Indicates whether this node will be involved in the flow of payment for
     * the inventory. When set to true, the advertising system in the
     * advertising_system_identifier field pays the seller in the
     * seller_identifier field, who is responsible for paying the previous
     * node in the chain. When set to false, this node is not involved in the
     * flow of payment for the inventory.
     *
     * Generated from protobuf field <code>optional bool handles_payment = 6;</code>
     * @return bool
     */
    public function getHandlesPayment()
    {
        return isset($this->handles_payment) ? $this->handles_payment : false;
    }

    public function hasHandlesPayment()
    {
        return isset($this->handles_payment);
    }

    public function clearHandlesPayment()
    {
        unset($this->handles_payment);
    }

    /**
     * Indicates whether this node will be involved in the flow of payment for
     * the inventory. When set to true, the advertising system in the
     * advertising_system_identifier field pays the seller in the
     * seller_identifier field, who is responsible for paying the previous
     * node in the chain. When set to false, this node is not involved in the
     * flow of payment for the inventory.
     *
     * Generated from protobuf field <code>optional bool handles_payment = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setHandlesPayment($var)
    {
        GPBUtil::checkBool($var);
        $this->handles_payment = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(SupplyChainNode::class, \BidRequest_SupplyChain_SupplyChainNode::class);

