<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidResponse\Ad\ImpressionTrackingResource;

use UnexpectedValueException;

/**
 * Additional context provided for rendering.
 *
 * Protobuf type <code>BidResponse.Ad.ImpressionTrackingResource.Context</code>
 */
class Context
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_CONTEXT = 0;</code>
     */
    const UNKNOWN_CONTEXT = 0;
    /**
     * Currently not supported.
     *
     * Generated from protobuf enum <code>OMID = 1;</code>
     */
    const OMID = 1;

    private static $valueToName = [
        self::UNKNOWN_CONTEXT => 'UNKNOWN_CONTEXT',
        self::OMID => 'OMID',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Context::class, \BidResponse_Ad_ImpressionTrackingResource_Context::class);

