<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidResponse\Ad\NativeAd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>BidResponse.Ad.NativeAd.Image</code>
 */
class Image extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string url = 1;</code>
     */
    protected $url = null;
    /**
     * Image width and height are specified in pixels. You may provide a
     * larger image than was requested, so long as the aspect ratio is
     * preserved.
     *
     * Generated from protobuf field <code>optional int32 width = 2;</code>
     */
    protected $width = null;
    /**
     * Generated from protobuf field <code>optional int32 height = 3;</code>
     */
    protected $height = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $url
     *     @type int $width
     *           Image width and height are specified in pixels. You may provide a
     *           larger image than was requested, so long as the aspect ratio is
     *           preserved.
     *     @type int $height
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RealtimeBidding::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string url = 1;</code>
     * @return string
     */
    public function getUrl()
    {
        return isset($this->url) ? $this->url : '';
    }

    public function hasUrl()
    {
        return isset($this->url);
    }

    public function clearUrl()
    {
        unset($this->url);
    }

    /**
     * Generated from protobuf field <code>optional string url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * Image width and height are specified in pixels. You may provide a
     * larger image than was requested, so long as the aspect ratio is
     * preserved.
     *
     * Generated from protobuf field <code>optional int32 width = 2;</code>
     * @return int
     */
    public function getWidth()
    {
        return isset($this->width) ? $this->width : 0;
    }

    public function hasWidth()
    {
        return isset($this->width);
    }

    public function clearWidth()
    {
        unset($this->width);
    }

    /**
     * Image width and height are specified in pixels. You may provide a
     * larger image than was requested, so long as the aspect ratio is
     * preserved.
     *
     * Generated from protobuf field <code>optional int32 width = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setWidth($var)
    {
        GPBUtil::checkInt32($var);
        $this->width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 height = 3;</code>
     * @return int
     */
    public function getHeight()
    {
        return isset($this->height) ? $this->height : 0;
    }

    public function hasHeight()
    {
        return isset($this->height);
    }

    public function clearHeight()
    {
        unset($this->height);
    }

    /**
     * Generated from protobuf field <code>optional int32 height = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->height = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Image::class, \BidResponse_Ad_NativeAd_Image::class);

