<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidResponse\Ad;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * An ad that will be rendered by an SDK known to the buyer. This can only
 * be used when the BidRequest included a mobile.installed_sdk submessage.
 *
 * Generated from protobuf message <code>BidResponse.Ad.SdkRenderedAd</code>
 */
class SdkRenderedAd extends \Google\Protobuf\Internal\Message
{
    /**
     * The identifier for the SDK that will render the ad. Must match a
     * mobile.installed_sdk.id sent in the corresponding bid request.
     *
     * Generated from protobuf field <code>optional string id = 1;</code>
     */
    protected $id = null;
    /**
     * Data to pass to the SDK in order to render the ad. This data is opaque
     * to the publisher and to Google.
     *
     * Generated from protobuf field <code>optional string rendering_data = 2;</code>
     */
    protected $rendering_data = null;
    /**
     * Generated from protobuf field <code>optional .BidResponse.Ad.SdkRenderedAd.DeclaredAd declared_ad = 6;</code>
     */
    protected $declared_ad = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           The identifier for the SDK that will render the ad. Must match a
     *           mobile.installed_sdk.id sent in the corresponding bid request.
     *     @type string $rendering_data
     *           Data to pass to the SDK in order to render the ad. This data is opaque
     *           to the publisher and to Google.
     *     @type \BidResponse\Ad\SdkRenderedAd\DeclaredAd $declared_ad
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RealtimeBidding::initOnce();
        parent::__construct($data);
    }

    /**
     * The identifier for the SDK that will render the ad. Must match a
     * mobile.installed_sdk.id sent in the corresponding bid request.
     *
     * Generated from protobuf field <code>optional string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return isset($this->id) ? $this->id : '';
    }

    public function hasId()
    {
        return isset($this->id);
    }

    public function clearId()
    {
        unset($this->id);
    }

    /**
     * The identifier for the SDK that will render the ad. Must match a
     * mobile.installed_sdk.id sent in the corresponding bid request.
     *
     * Generated from protobuf field <code>optional string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Data to pass to the SDK in order to render the ad. This data is opaque
     * to the publisher and to Google.
     *
     * Generated from protobuf field <code>optional string rendering_data = 2;</code>
     * @return string
     */
    public function getRenderingData()
    {
        return isset($this->rendering_data) ? $this->rendering_data : '';
    }

    public function hasRenderingData()
    {
        return isset($this->rendering_data);
    }

    public function clearRenderingData()
    {
        unset($this->rendering_data);
    }

    /**
     * Data to pass to the SDK in order to render the ad. This data is opaque
     * to the publisher and to Google.
     *
     * Generated from protobuf field <code>optional string rendering_data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRenderingData($var)
    {
        GPBUtil::checkString($var, True);
        $this->rendering_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .BidResponse.Ad.SdkRenderedAd.DeclaredAd declared_ad = 6;</code>
     * @return \BidResponse\Ad\SdkRenderedAd\DeclaredAd|null
     */
    public function getDeclaredAd()
    {
        return $this->declared_ad;
    }

    public function hasDeclaredAd()
    {
        return isset($this->declared_ad);
    }

    public function clearDeclaredAd()
    {
        unset($this->declared_ad);
    }

    /**
     * Generated from protobuf field <code>optional .BidResponse.Ad.SdkRenderedAd.DeclaredAd declared_ad = 6;</code>
     * @param \BidResponse\Ad\SdkRenderedAd\DeclaredAd $var
     * @return $this
     */
    public function setDeclaredAd($var)
    {
        GPBUtil::checkMessage($var, \BidResponse\Ad\SdkRenderedAd\DeclaredAd::class);
        $this->declared_ad = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(SdkRenderedAd::class, \BidResponse_Ad_SdkRenderedAd::class);

