<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidResponse\Ad;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Advertiser's SKAdNetwork information to support app installation
 * attribution for iOS 14 and later. Apple's SKAdNetwork API helps
 * advertisers measure ad-driven app installation by sending a postback
 * to the ad network after a successful install. Ad networks will need
 * to send their network ID and signed advertiser information to allow
 * an install to be attributed to the ad impression.
 * For more info visit:
 * https://developer.apple.com/documentation/storekit/skadnetwork
 *
 * Generated from protobuf message <code>BidResponse.Ad.SKAdNetworkResponse</code>
 */
class SKAdNetworkResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Version of SKAdNetwork supported by the advertiser. Also used to
     * specify how the signature was generated by the advertiser. This
     * should match the version from BidRequest.mobile.skad.version.
     *
     * Generated from protobuf field <code>optional string version = 1;</code>
     */
    protected $version = null;
    /**
     * Ad network identifier used in signature. This should match one of the
     * items in BidRequest.mobile.skad.skadnetids.
     *
     * Generated from protobuf field <code>optional string network = 2;</code>
     */
    protected $network = null;
    /**
     * Campaign ID compatible with Apple's spec. Used in SKAdNetwork 3.0 and
     * below. Replaced by Source Identifier (`source_identifier` field) in
     * SKAdNetwork 4.0 and above.
     *
     * Generated from protobuf field <code>optional int64 campaign = 3;</code>
     */
    protected $campaign = null;
    /**
     * A four-digit integer that ad networks define to represent the ad
     * campaign. Used in SKAdNetwork 4.0+ and replaces the `campaign` field.
     *
     * Generated from protobuf field <code>optional int64 source_identifier = 11;</code>
     */
    protected $source_identifier = null;
    /**
     * ID of advertiser's app in Apple's app store.
     *
     * Generated from protobuf field <code>optional string itunesitem = 4;</code>
     */
    protected $itunesitem = null;
    /**
     * ID of custom product page to display (for iOS 15 or later).
     * If not specified, default product page will be displayed.
     * See https://developer.apple.com/app-store/custom-product-pages/
     * for more details about custom product pages.
     *
     * Generated from protobuf field <code>optional string product_page_id = 12;</code>
     */
    protected $product_page_id = null;
    /**
     * Generated from protobuf field <code>repeated .BidResponse.Ad.SKAdNetworkResponse.Fidelity fidelities = 9;</code>
     */
    private $fidelities;
    /**
     * A unique all-lowercase UUID generated by the advertiser to use for
     * generating the signature.
     * Note:  This field will be deprecated in favor of the
     * BidResponse.ad.skadn.fidelities.nonce field to support multiple
     * fidelity types.
     *
     * Generated from protobuf field <code>optional string nonce = 5;</code>
     */
    protected $nonce = null;
    /**
     * ID of publisher's app in Apple's app store. This should match the ID
     * from BidRequest.mobile.skad.sourceapp.
     *
     * Generated from protobuf field <code>optional string sourceapp = 6;</code>
     */
    protected $sourceapp = null;
    /**
     * Unix time in millis used at the time of signature generation.
     * Note:  This field will be deprecated in favor of the
     * BidResponse.ad.skadn.fidelities.timestamp field to support multiple
     * fidelity types.
     *
     * Generated from protobuf field <code>optional int64 timestamp = 7;</code>
     */
    protected $timestamp = null;
    /**
     * SKAdNetwork signature as specified by Apple.
     * Note:  This field will be deprecated in favor of the
     * BidResponse.ad.skadn.fidelities.signature field to support multiple
     * fidelity types.
     *
     * Generated from protobuf field <code>optional string signature = 8;</code>
     */
    protected $signature = null;
    /**
     * Generated from protobuf field <code>optional .BidResponse.Ad.SKAdNetworkResponse.SKOverlay skoverlay = 13;</code>
     */
    protected $skoverlay = null;
    /**
     * Generated from protobuf field <code>optional .BidResponse.Ad.SKAdNetworkResponse.SKAdNetworkOptions skadn_options = 10;</code>
     */
    protected $skadn_options = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $version
     *           Version of SKAdNetwork supported by the advertiser. Also used to
     *           specify how the signature was generated by the advertiser. This
     *           should match the version from BidRequest.mobile.skad.version.
     *     @type string $network
     *           Ad network identifier used in signature. This should match one of the
     *           items in BidRequest.mobile.skad.skadnetids.
     *     @type int|string $campaign
     *           Campaign ID compatible with Apple's spec. Used in SKAdNetwork 3.0 and
     *           below. Replaced by Source Identifier (`source_identifier` field) in
     *           SKAdNetwork 4.0 and above.
     *     @type int|string $source_identifier
     *           A four-digit integer that ad networks define to represent the ad
     *           campaign. Used in SKAdNetwork 4.0+ and replaces the `campaign` field.
     *     @type string $itunesitem
     *           ID of advertiser's app in Apple's app store.
     *     @type string $product_page_id
     *           ID of custom product page to display (for iOS 15 or later).
     *           If not specified, default product page will be displayed.
     *           See https://developer.apple.com/app-store/custom-product-pages/
     *           for more details about custom product pages.
     *     @type array<\BidResponse\Ad\SKAdNetworkResponse\Fidelity>|\Google\Protobuf\Internal\RepeatedField $fidelities
     *     @type string $nonce
     *           A unique all-lowercase UUID generated by the advertiser to use for
     *           generating the signature.
     *           Note:  This field will be deprecated in favor of the
     *           BidResponse.ad.skadn.fidelities.nonce field to support multiple
     *           fidelity types.
     *     @type string $sourceapp
     *           ID of publisher's app in Apple's app store. This should match the ID
     *           from BidRequest.mobile.skad.sourceapp.
     *     @type int|string $timestamp
     *           Unix time in millis used at the time of signature generation.
     *           Note:  This field will be deprecated in favor of the
     *           BidResponse.ad.skadn.fidelities.timestamp field to support multiple
     *           fidelity types.
     *     @type string $signature
     *           SKAdNetwork signature as specified by Apple.
     *           Note:  This field will be deprecated in favor of the
     *           BidResponse.ad.skadn.fidelities.signature field to support multiple
     *           fidelity types.
     *     @type \BidResponse\Ad\SKAdNetworkResponse\SKOverlay $skoverlay
     *     @type \BidResponse\Ad\SKAdNetworkResponse\SKAdNetworkOptions $skadn_options
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RealtimeBidding::initOnce();
        parent::__construct($data);
    }

    /**
     * Version of SKAdNetwork supported by the advertiser. Also used to
     * specify how the signature was generated by the advertiser. This
     * should match the version from BidRequest.mobile.skad.version.
     *
     * Generated from protobuf field <code>optional string version = 1;</code>
     * @return string
     */
    public function getVersion()
    {
        return isset($this->version) ? $this->version : '';
    }

    public function hasVersion()
    {
        return isset($this->version);
    }

    public function clearVersion()
    {
        unset($this->version);
    }

    /**
     * Version of SKAdNetwork supported by the advertiser. Also used to
     * specify how the signature was generated by the advertiser. This
     * should match the version from BidRequest.mobile.skad.version.
     *
     * Generated from protobuf field <code>optional string version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Ad network identifier used in signature. This should match one of the
     * items in BidRequest.mobile.skad.skadnetids.
     *
     * Generated from protobuf field <code>optional string network = 2;</code>
     * @return string
     */
    public function getNetwork()
    {
        return isset($this->network) ? $this->network : '';
    }

    public function hasNetwork()
    {
        return isset($this->network);
    }

    public function clearNetwork()
    {
        unset($this->network);
    }

    /**
     * Ad network identifier used in signature. This should match one of the
     * items in BidRequest.mobile.skad.skadnetids.
     *
     * Generated from protobuf field <code>optional string network = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNetwork($var)
    {
        GPBUtil::checkString($var, True);
        $this->network = $var;

        return $this;
    }

    /**
     * Campaign ID compatible with Apple's spec. Used in SKAdNetwork 3.0 and
     * below. Replaced by Source Identifier (`source_identifier` field) in
     * SKAdNetwork 4.0 and above.
     *
     * Generated from protobuf field <code>optional int64 campaign = 3;</code>
     * @return int|string
     */
    public function getCampaign()
    {
        return isset($this->campaign) ? $this->campaign : 0;
    }

    public function hasCampaign()
    {
        return isset($this->campaign);
    }

    public function clearCampaign()
    {
        unset($this->campaign);
    }

    /**
     * Campaign ID compatible with Apple's spec. Used in SKAdNetwork 3.0 and
     * below. Replaced by Source Identifier (`source_identifier` field) in
     * SKAdNetwork 4.0 and above.
     *
     * Generated from protobuf field <code>optional int64 campaign = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCampaign($var)
    {
        GPBUtil::checkInt64($var);
        $this->campaign = $var;

        return $this;
    }

    /**
     * A four-digit integer that ad networks define to represent the ad
     * campaign. Used in SKAdNetwork 4.0+ and replaces the `campaign` field.
     *
     * Generated from protobuf field <code>optional int64 source_identifier = 11;</code>
     * @return int|string
     */
    public function getSourceIdentifier()
    {
        return isset($this->source_identifier) ? $this->source_identifier : 0;
    }

    public function hasSourceIdentifier()
    {
        return isset($this->source_identifier);
    }

    public function clearSourceIdentifier()
    {
        unset($this->source_identifier);
    }

    /**
     * A four-digit integer that ad networks define to represent the ad
     * campaign. Used in SKAdNetwork 4.0+ and replaces the `campaign` field.
     *
     * Generated from protobuf field <code>optional int64 source_identifier = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSourceIdentifier($var)
    {
        GPBUtil::checkInt64($var);
        $this->source_identifier = $var;

        return $this;
    }

    /**
     * ID of advertiser's app in Apple's app store.
     *
     * Generated from protobuf field <code>optional string itunesitem = 4;</code>
     * @return string
     */
    public function getItunesitem()
    {
        return isset($this->itunesitem) ? $this->itunesitem : '';
    }

    public function hasItunesitem()
    {
        return isset($this->itunesitem);
    }

    public function clearItunesitem()
    {
        unset($this->itunesitem);
    }

    /**
     * ID of advertiser's app in Apple's app store.
     *
     * Generated from protobuf field <code>optional string itunesitem = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setItunesitem($var)
    {
        GPBUtil::checkString($var, True);
        $this->itunesitem = $var;

        return $this;
    }

    /**
     * ID of custom product page to display (for iOS 15 or later).
     * If not specified, default product page will be displayed.
     * See https://developer.apple.com/app-store/custom-product-pages/
     * for more details about custom product pages.
     *
     * Generated from protobuf field <code>optional string product_page_id = 12;</code>
     * @return string
     */
    public function getProductPageId()
    {
        return isset($this->product_page_id) ? $this->product_page_id : '';
    }

    public function hasProductPageId()
    {
        return isset($this->product_page_id);
    }

    public function clearProductPageId()
    {
        unset($this->product_page_id);
    }

    /**
     * ID of custom product page to display (for iOS 15 or later).
     * If not specified, default product page will be displayed.
     * See https://developer.apple.com/app-store/custom-product-pages/
     * for more details about custom product pages.
     *
     * Generated from protobuf field <code>optional string product_page_id = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setProductPageId($var)
    {
        GPBUtil::checkString($var, True);
        $this->product_page_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .BidResponse.Ad.SKAdNetworkResponse.Fidelity fidelities = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFidelities()
    {
        return $this->fidelities;
    }

    /**
     * Generated from protobuf field <code>repeated .BidResponse.Ad.SKAdNetworkResponse.Fidelity fidelities = 9;</code>
     * @param array<\BidResponse\Ad\SKAdNetworkResponse\Fidelity>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFidelities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \BidResponse\Ad\SKAdNetworkResponse\Fidelity::class);
        $this->fidelities = $arr;

        return $this;
    }

    /**
     * A unique all-lowercase UUID generated by the advertiser to use for
     * generating the signature.
     * Note:  This field will be deprecated in favor of the
     * BidResponse.ad.skadn.fidelities.nonce field to support multiple
     * fidelity types.
     *
     * Generated from protobuf field <code>optional string nonce = 5;</code>
     * @return string
     */
    public function getNonce()
    {
        return isset($this->nonce) ? $this->nonce : '';
    }

    public function hasNonce()
    {
        return isset($this->nonce);
    }

    public function clearNonce()
    {
        unset($this->nonce);
    }

    /**
     * A unique all-lowercase UUID generated by the advertiser to use for
     * generating the signature.
     * Note:  This field will be deprecated in favor of the
     * BidResponse.ad.skadn.fidelities.nonce field to support multiple
     * fidelity types.
     *
     * Generated from protobuf field <code>optional string nonce = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setNonce($var)
    {
        GPBUtil::checkString($var, True);
        $this->nonce = $var;

        return $this;
    }

    /**
     * ID of publisher's app in Apple's app store. This should match the ID
     * from BidRequest.mobile.skad.sourceapp.
     *
     * Generated from protobuf field <code>optional string sourceapp = 6;</code>
     * @return string
     */
    public function getSourceapp()
    {
        return isset($this->sourceapp) ? $this->sourceapp : '';
    }

    public function hasSourceapp()
    {
        return isset($this->sourceapp);
    }

    public function clearSourceapp()
    {
        unset($this->sourceapp);
    }

    /**
     * ID of publisher's app in Apple's app store. This should match the ID
     * from BidRequest.mobile.skad.sourceapp.
     *
     * Generated from protobuf field <code>optional string sourceapp = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceapp($var)
    {
        GPBUtil::checkString($var, True);
        $this->sourceapp = $var;

        return $this;
    }

    /**
     * Unix time in millis used at the time of signature generation.
     * Note:  This field will be deprecated in favor of the
     * BidResponse.ad.skadn.fidelities.timestamp field to support multiple
     * fidelity types.
     *
     * Generated from protobuf field <code>optional int64 timestamp = 7;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return isset($this->timestamp) ? $this->timestamp : 0;
    }

    public function hasTimestamp()
    {
        return isset($this->timestamp);
    }

    public function clearTimestamp()
    {
        unset($this->timestamp);
    }

    /**
     * Unix time in millis used at the time of signature generation.
     * Note:  This field will be deprecated in favor of the
     * BidResponse.ad.skadn.fidelities.timestamp field to support multiple
     * fidelity types.
     *
     * Generated from protobuf field <code>optional int64 timestamp = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * SKAdNetwork signature as specified by Apple.
     * Note:  This field will be deprecated in favor of the
     * BidResponse.ad.skadn.fidelities.signature field to support multiple
     * fidelity types.
     *
     * Generated from protobuf field <code>optional string signature = 8;</code>
     * @return string
     */
    public function getSignature()
    {
        return isset($this->signature) ? $this->signature : '';
    }

    public function hasSignature()
    {
        return isset($this->signature);
    }

    public function clearSignature()
    {
        unset($this->signature);
    }

    /**
     * SKAdNetwork signature as specified by Apple.
     * Note:  This field will be deprecated in favor of the
     * BidResponse.ad.skadn.fidelities.signature field to support multiple
     * fidelity types.
     *
     * Generated from protobuf field <code>optional string signature = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, True);
        $this->signature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .BidResponse.Ad.SKAdNetworkResponse.SKOverlay skoverlay = 13;</code>
     * @return \BidResponse\Ad\SKAdNetworkResponse\SKOverlay|null
     */
    public function getSkoverlay()
    {
        return $this->skoverlay;
    }

    public function hasSkoverlay()
    {
        return isset($this->skoverlay);
    }

    public function clearSkoverlay()
    {
        unset($this->skoverlay);
    }

    /**
     * Generated from protobuf field <code>optional .BidResponse.Ad.SKAdNetworkResponse.SKOverlay skoverlay = 13;</code>
     * @param \BidResponse\Ad\SKAdNetworkResponse\SKOverlay $var
     * @return $this
     */
    public function setSkoverlay($var)
    {
        GPBUtil::checkMessage($var, \BidResponse\Ad\SKAdNetworkResponse\SKOverlay::class);
        $this->skoverlay = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .BidResponse.Ad.SKAdNetworkResponse.SKAdNetworkOptions skadn_options = 10;</code>
     * @return \BidResponse\Ad\SKAdNetworkResponse\SKAdNetworkOptions|null
     */
    public function getSkadnOptions()
    {
        return $this->skadn_options;
    }

    public function hasSkadnOptions()
    {
        return isset($this->skadn_options);
    }

    public function clearSkadnOptions()
    {
        unset($this->skadn_options);
    }

    /**
     * Generated from protobuf field <code>optional .BidResponse.Ad.SKAdNetworkResponse.SKAdNetworkOptions skadn_options = 10;</code>
     * @param \BidResponse\Ad\SKAdNetworkResponse\SKAdNetworkOptions $var
     * @return $this
     */
    public function setSkadnOptions($var)
    {
        GPBUtil::checkMessage($var, \BidResponse\Ad\SKAdNetworkResponse\SKAdNetworkOptions::class);
        $this->skadn_options = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(SKAdNetworkResponse::class, \BidResponse_Ad_SKAdNetworkResponse::class);

