<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime-bidding.proto

namespace BidRequest\PublisherFirstPartyId;

use UnexpectedValueException;

/**
 * Specifies how an ID is scoped and the type of requests it is used with.
 *
 * Protobuf type <code>BidRequest.PublisherFirstPartyId.IdType</code>
 */
class IdType
{
    /**
     * A default value that should not be used.
     *
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * A site-scoped cookie for requests from web browsers.
     *
     * Generated from protobuf enum <code>SITE_SCOPED_COOKIE = 1;</code>
     */
    const SITE_SCOPED_COOKIE = 1;

    private static $valueToName = [
        self::UNKNOWN => 'UNKNOWN',
        self::SITE_SCOPED_COOKIE => 'SITE_SCOPED_COOKIE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(IdType::class, \BidRequest_PublisherFirstPartyId_IdType::class);

